package workflowsystem.util;

public class WfSqlCommon {

	/** SQL Select */

	/* Search all records in Company table */
	public static String SELECTSQL_COMPANY_001 = "SELECT * FROM MST_COMPANY ORDER BY COMPANYID ";

	/* Search records in Company table by Company ID */
	public static String SELECTSQL_COMPANY_002 = "SELECT * FROM MST_COMPANY WHERE COMPANYID = ? ";

	/* Search records in Company table by Company Code */
	public static String SELECTSQL_COMPANY_003 = "SELECT * FROM MST_COMPANY WHERE COMPANYCODE = ? ";

	/* Search all records in Document Type table */
	public static String SELECTSQL_DOCUMENTTYPE_001 = "SELECT * FROM MST_DOCUMENTTYPE ORDER BY DOCUMENTTYPEID ";

	/* Search records in Document Type table by Document Type ID */
	public static String SELECTSQL_DOCUMENTTYPE_002 = "SELECT * FROM MST_DOCUMENTTYPE WHERE DOCUMENTTYPEID = ? ";

	/* Search records in Document Type table by Document Type Code */
	public static String SELECTSQL_DOCUMENTTYPE_003 = "SELECT * FROM MST_DOCUMENTTYPE WHERE DOCUMENTTYPECODE = ? ";

	/* Search all records in Phase table */
	public static String SELECTSQL_PHASE_001 = "SELECT * FROM MST_PHASE ORDER BY PHASEID ";

	/* Search records in Phase table by Phase ID */
	public static String SELECTSQL_PHASE_002 = "SELECT * FROM MST_PHASE WHERE PHASEID = ? ";

	/* Search records in Phase table by Phase Code */
	public static String SELECTSQL_PHASE_003 = "SELECT * FROM MST_PHASE WHERE PHASECODE = ? ";

	/* Search all records in Module table */
	public static String SELECTSQL_MODULE_001 = "SELECT * FROM MST_MODULE ORDER BY MODULESEQUENCE ";
	
	/* Search records in Module table by Module ID */
	public static String SELECTSQL_MODULE_002 = "SELECT * FROM MST_MODULE WHERE MODULEID = ? ORDER BY MODULESEQUENCE ";
	
	/* Search records in Module table by Module Name */
	public static String SELECTSQL_MODULE_003 = "SELECT * FROM MST_MODULE WHERE MODULENAME = ? ORDER BY MODULESEQUENCE ";
	
	/* Search all modules by User ID */
	public static String SELECTSQL_MODULE_004 = "SELECT DISTINCT "
			+ "     MST_MODULE.MODULEID AS MODULEID, "
			+ "     MST_MODULE.MODULENAME AS MODULENAME, "
			+ "     MST_MODULE.MODULESEQUENCE AS MODULESEQUENCE, "
			+ "     MST_MODULE.URLPATTERN AS URLPATTERN "
			+ " FROM MST_ACCESSTYPEDETAIL "
			+ " INNER JOIN MST_ACCESSTYPE "
			+ "     ON MST_ACCESSTYPE.ACCESSTYPEID = MST_ACCESSTYPEDETAIL.ACCESSTYPEID "
			+ " INNER JOIN MST_PROGRAM "
			+ "     ON MST_PROGRAM.PROGRAMID = MST_ACCESSTYPEDETAIL.PROGRAMID "
			+ " INNER JOIN MST_MODULE "
			+ "     ON MST_MODULE.MODULEID = MST_PROGRAM.MODULEID "
			+ " INNER JOIN MST_USER "
			+ "     ON MST_USER.ACCESSTYPEID = MST_ACCESSTYPE.ACCESSTYPEID "
			+ " WHERE MST_USER.USERID = ? "
			+ " ORDER BY MST_MODULE.MODULESEQUENCE ";
	
	/* Search all records in Program table */
	public static String SELECTSQL_PROGRAM_001 = "SELECT "
			+ "     MST_PROGRAM.PROGRAMID AS PROGRAMID, "
			+ "     MST_PROGRAM.PROGRAMNAME AS PROGRAMNAME, "
			+ "     MST_MODULE.MODULENAME AS MODULENAME, "
			+ "     MST_PROGRAM.JAVASERVLETREFERENCE AS JAVASERVLETREFERENCE, "
			+ "     MST_PROGRAM.URLPATTERN AS URLPATTERN, "
			+ "     MST_PROGRAM.WITHINTHEMENU AS WITHINTHEMENU "
			+ " FROM MST_PROGRAM "
			+ " INNER JOIN MST_MODULE "
			+ "     ON MST_PROGRAM.MODULEID = MST_MODULE.MODULEID "
			+ " ORDER BY PROGRAMID ";
	
	/* Search records in Program table by Program ID */
	public static String SELECTSQL_PROGRAM_002 = "SELECT "
			+ "     MST_PROGRAM.PROGRAMID AS PROGRAMID, "
			+ "     MST_PROGRAM.PROGRAMNAME AS PROGRAMNAME, "
			+ "     MST_MODULE.MODULENAME AS MODULENAME, "
			+ "     MST_PROGRAM.JAVASERVLETREFERENCE AS JAVASERVLETREFERENCE, "
			+ "     MST_PROGRAM.URLPATTERN AS URLPATTERN, "
			+ "     MST_PROGRAM.WITHINTHEMENU AS WITHINTHEMENU "
			+ " FROM MST_PROGRAM "
			+ " INNER JOIN MST_MODULE "
			+ "     ON MST_PROGRAM.MODULEID = MST_MODULE.MODULEID "
			+ " WHERE MST_PROGRAM.PROGRAMID = ? ";
	
	/* Search records in Program table by Program Name */
	public static String SELECTSQL_PROGRAM_003 = "SELECT "
			+ "     MST_PROGRAM.PROGRAMID AS PROGRAMID, "
			+ "     MST_PROGRAM.PROGRAMNAME AS PROGRAMNAME, "
			+ "     MST_MODULE.MODULENAME AS MODULENAME, "
			+ "     MST_PROGRAM.JAVASERVLETREFERENCE AS JAVASERVLETREFERENCE, "
			+ "     MST_PROGRAM.URLPATTERN AS URLPATTERN, "
			+ "     MST_PROGRAM.WITHINTHEMENU AS WITHINTHEMENU "
			+ " FROM MST_PROGRAM "
			+ " INNER JOIN MST_MODULE "
			+ "     ON MST_PROGRAM.MODULEID = MST_MODULE.MODULEID "
			+ " WHERE MST_PROGRAM.PROGRAMNAME = ? ";
	
	/* Search records in Program table by Java Servlet Reference */
	public static String SELECTSQL_PROGRAM_004 = "SELECT "
			+ "     MST_PROGRAM.PROGRAMID AS PROGRAMID, "
			+ "     MST_PROGRAM.PROGRAMNAME AS PROGRAMNAME, "
			+ "     MST_MODULE.MODULENAME AS MODULENAME, "
			+ "     MST_PROGRAM.JAVASERVLETREFERENCE AS JAVASERVLETREFERENCE, "
			+ "     MST_PROGRAM.URLPATTERN AS URLPATTERN, "
			+ "     MST_PROGRAM.WITHINTHEMENU AS WITHINTHEMENU "
			+ " FROM MST_PROGRAM "
			+ " INNER JOIN MST_MODULE "
			+ "     ON MST_PROGRAM.MODULEID = MST_MODULE.MODULEID "
			+ " WHERE MST_PROGRAM.JAVASERVLETREFERENCE = ? ";
	
	/* Search records in Program table that are not yet selected */
	public static String SELECTSQL_PROGRAM_005 = "SELECT "
			+ "     MST_PROGRAM.PROGRAMID AS PROGRAMID, "
			+ "     MST_PROGRAM.PROGRAMNAME AS PROGRAMNAME, "
			+ "     MST_MODULE.MODULENAME AS MODULENAME, "
			+ "     MST_PROGRAM.JAVASERVLETREFERENCE AS JAVASERVLETREFERENCE, "
			+ "     MST_PROGRAM.URLPATTERN AS URLPATTERN, "
			+ "     MST_PROGRAM.WITHINTHEMENU AS WITHINTHEMENU "
			+ " FROM MST_PROGRAM "
			+ " INNER JOIN MST_MODULE "
			+ "     ON MST_PROGRAM.MODULEID = MST_MODULE.MODULEID "
			+ " WHERE NOT EXISTS "
			+ "     ( SELECT NULL "
			+ "       FROM MST_ACCESSTYPEDETAIL "
			+ "       WHERE MST_ACCESSTYPEDETAIL.PROGRAMID = MST_PROGRAM.PROGRAMID AND "
			+ "             MST_ACCESSTYPEDETAIL.ACCESSTYPEID = ? "
			+ "     ) ";
	
	/* Search records in Program table that are not yet selected for Edit mode */
	public static String SELECTSQL_PROGRAM_005_ADD01 = " OR MST_PROGRAM.PROGRAMNAME = ? ";
	
	/* Search all records in Access Type table */
	public static String SELECTSQL_ACCESSTYPE_001 = "SELECT * FROM MST_ACCESSTYPE ORDER BY ACCESSTYPEID ";
	
	/* Search records in Access Type table by Access Type ID */
	public static String SELECTSQL_ACCESSTYPE_002 = "SELECT * FROM MST_ACCESSTYPE WHERE ACCESSTYPEID = ? ";
	
	/* Search records in Access Type table by Access Type Code */
	public static String SELECTSQL_ACCESSTYPE_003 = "SELECT * FROM MST_ACCESSTYPE WHERE ACCESSTYPECODE = ? ";
	
	/* Search all records in Access Type Detail table by Access Type ID */
	public static String SELECTSQL_ACCESSTYPEDETAIL_001 = "SELECT "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSTYPEDETAILID AS ACCESSTYPEDETAILID, "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSTYPEID AS ACCESSTYPEID, "
			+ " 	MST_PROGRAM.PROGRAMNAME AS PROGRAMNAME, "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSRIGHT AS ACCESSRIGHT, "
			+ " 	MST_PROGRAM.JAVASERVLETREFERENCE AS JAVASERVLETREFERENCE, "
			+ " 	MST_MODULE.MODULENAME AS MODULENAME, "
			+ " 	MST_PROGRAM.URLPATTERN AS URLPATTERN, "
			+ " 	MST_PROGRAM.WITHINTHEMENU AS WITHINTHEMENU "
			+ " FROM MST_ACCESSTYPEDETAIL "
			+ " INNER JOIN MST_PROGRAM "
			+ " 	ON MST_ACCESSTYPEDETAIL.PROGRAMID = MST_PROGRAM.PROGRAMID "
			+ " INNER JOIN MST_MODULE "
			+ " 	ON MST_MODULE.MODULEID = MST_PROGRAM.MODULEID "
			+ " WHERE MST_ACCESSTYPEDETAIL.ACCESSTYPEID = ? "
			+ " ORDER BY MST_ACCESSTYPEDETAIL.ACCESSTYPEDETAILID ";
	
	/* Search a record in Access Type Details table by Access Type Detail ID */
	public static String SELECTSQL_ACCESSTYPEDETAIL_002 = "SELECT "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSTYPEDETAILID AS ACCESSTYPEDETAILID, "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSTYPEID AS ACCESSTYPEID, "
			+ " 	MST_PROGRAM.PROGRAMNAME AS PROGRAMNAME, "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSRIGHT AS ACCESSRIGHT, "
			+ " 	MST_PROGRAM.JAVASERVLETREFERENCE AS JAVASERVLETREFERENCE, "
			+ " 	MST_MODULE.MODULENAME AS MODULENAME, "
			+ " 	MST_PROGRAM.URLPATTERN AS URLPATTERN, "
			+ " 	MST_PROGRAM.WITHINTHEMENU AS WITHINTHEMENU "
			+ " FROM MST_ACCESSTYPEDETAIL "
			+ " INNER JOIN MST_PROGRAM "
			+ " 	ON MST_ACCESSTYPEDETAIL.PROGRAMID = MST_PROGRAM.PROGRAMID "
			+ " INNER JOIN MST_MODULE "
			+ " 	ON MST_MODULE.MODULEID = MST_PROGRAM.MODULEID "
			+ " WHERE MST_ACCESSTYPEDETAIL.ACCESSTYPEDETAILID = ? "
			+ " ORDER BY MST_ACCESSTYPEDETAIL.ACCESSTYPEDETAILID ";
	
	/* Search records in Access Type Detail table by Program Name and Access Type ID */
	public static String SELECTSQL_ACCESSTYPEDETAIL_003 = "SELECT "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSTYPEDETAILID AS ACCESSTYPEDETAILID, "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSTYPEID AS ACCESSTYPEID, "
			+ " 	MST_PROGRAM.PROGRAMNAME AS PROGRAMNAME, "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSRIGHT AS ACCESSRIGHT, "
			+ " 	MST_PROGRAM.JAVASERVLETREFERENCE AS JAVASERVLETREFERENCE, "
			+ " 	MST_MODULE.MODULENAME AS MODULENAME, "
			+ " 	MST_PROGRAM.URLPATTERN AS URLPATTERN, "
			+ " 	MST_PROGRAM.WITHINTHEMENU AS WITHINTHEMENU "
			+ " FROM MST_ACCESSTYPEDETAIL "
			+ " INNER JOIN MST_PROGRAM "
			+ " 	ON MST_ACCESSTYPEDETAIL.PROGRAMID = MST_PROGRAM.PROGRAMID "
			+ " INNER JOIN MST_MODULE "
			+ " 	ON MST_MODULE.MODULEID = MST_PROGRAM.MODULEID "
			+ " WHERE MST_PROGRAM.PROGRAMNAME = ? AND " 
			+ "       MST_ACCESSTYPEDETAIL.ACCESSTYPEDETAILID = ? "
			+ " ORDER BY MST_ACCESSTYPEDETAIL.ACCESSTYPEDETAILID ";
	
	/* Search records in Access Type Detail table by User */
	public static String SELECTSQL_ACCESSTYPEDETAIL_004 = "SELECT "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSTYPEDETAILID AS ACCESSTYPEDETAILID, "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSTYPEID AS ACCESSTYPEID, "
			+ " 	MST_PROGRAM.PROGRAMNAME AS PROGRAMNAME, "
			+ " 	MST_ACCESSTYPEDETAIL.ACCESSRIGHT AS ACCESSRIGHT, "
			+ " 	MST_PROGRAM.JAVASERVLETREFERENCE AS JAVASERVLETREFERENCE, "
			+ " 	MST_MODULE.MODULENAME AS MODULENAME, "
			+ " 	MST_PROGRAM.URLPATTERN AS URLPATTERN, "
			+ " 	MST_PROGRAM.WITHINTHEMENU AS WITHINTHEMENU "
			+ " FROM MST_USER "
			+ " INNER JOIN MST_ACCESSTYPE "
			+ " 	ON MST_USER.ACCESSTYPEID = MST_ACCESSTYPE.ACCESSTYPEID "
			+ " INNER JOIN MST_ACCESSTYPEDETAIL "
			+ "     ON MST_ACCESSTYPE.ACCESSTYPEID = MST_ACCESSTYPEDETAIL.ACCESSTYPEID "
			+ " INNER JOIN MST_PROGRAM "
			+ "     ON MST_PROGRAM.PROGRAMID = MST_ACCESSTYPEDETAIL.PROGRAMID "
			+ " INNER JOIN MST_MODULE "
			+ " 	ON MST_MODULE.MODULEID = MST_PROGRAM.MODULEID "
			+ " WHERE MST_USER.USERID = ? ";
	
	/* Search records in User table by User ID */
	public static String SELECTSQL_USER_001 = "SELECT "
			+ "		MST_USER.USERID AS USERID, "
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ " 	MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	MST_USER.USERPASSWORD AS USERPASSWORD, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_USER.USEREMAIL AS USEREMAIL, " 
			+ " 	MST_ACCESSTYPE.ACCESSTYPECODE AS ACCESSTYPECODE, "
			+ "     DATE_FORMAT(MST_USER.VALIDFROM,'%Y-%m-%d') AS VALIDFROM, "
			+ "     DATE_FORMAT(MST_USER.VALIDTO,'%Y-%m-%d') AS VALIDTO "
			+ " FROM MST_USER "
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON MST_USER.COMPANYID = MST_COMPANY.COMPANYID "
			+ " INNER JOIN MST_ACCESSTYPE "
			+ "     ON MST_USER.ACCESSTYPEID = MST_ACCESSTYPE.ACCESSTYPEID "
			+ " WHERE MST_USER.USERID = ? ";

	/* Search records in User table by User Name */
	public static String SELECTSQL_USER_002 = "SELECT "
			+ "		MST_USER.USERID AS USERID, "
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ " 	MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	MST_USER.USERPASSWORD AS USERPASSWORD, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_USER.USEREMAIL AS USEREMAIL, " 
			+ " 	MST_ACCESSTYPE.ACCESSTYPECODE AS ACCESSTYPECODE, "
			+ "     DATE_FORMAT(MST_USER.VALIDFROM,'%Y-%m-%d') AS VALIDFROM, "
			+ "     DATE_FORMAT(MST_USER.VALIDTO,'%Y-%m-%d') AS VALIDTO "
			+ " FROM MST_USER "
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON MST_USER.COMPANYID = MST_COMPANY.COMPANYID "
			+ " INNER JOIN MST_ACCESSTYPE "
			+ "     ON MST_USER.ACCESSTYPEID = MST_ACCESSTYPE.ACCESSTYPEID "
			+ " WHERE MST_USER.USERNAME = ? ";

	/* Search all records in User table */
	public static String SELECTSQL_USER_003 = "SELECT "
			+ "		MST_USER.USERID AS USERID, "
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ " 	MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	MST_USER.USERPASSWORD AS USERPASSWORD, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_USER.USEREMAIL AS USEREMAIL, " 
			+ " 	MST_ACCESSTYPE.ACCESSTYPECODE AS ACCESSTYPECODE, "
			+ "     DATE_FORMAT(MST_USER.VALIDFROM,'%Y-%m-%d') AS VALIDFROM, "
			+ "     DATE_FORMAT(MST_USER.VALIDTO,'%Y-%m-%d') AS VALIDTO "
			+ " FROM MST_USER "
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON MST_USER.COMPANYID = MST_COMPANY.COMPANYID "
			+ " INNER JOIN MST_ACCESSTYPE "
			+ "     ON MST_USER.ACCESSTYPEID = MST_ACCESSTYPE.ACCESSTYPEID ";

	/* Search records in User table by User E-mail */
	public static String SELECTSQL_USER_004 = "SELECT "
			+ "		MST_USER.USERID AS USERID, "
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ " 	MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	MST_USER.USERPASSWORD AS USERPASSWORD, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_USER.USEREMAIL AS USEREMAIL, " 
			+ " 	MST_ACCESSTYPE.ACCESSTYPECODE AS ACCESSTYPECODE, "
			+ "     DATE_FORMAT(MST_USER.VALIDFROM,'%Y-%m-%d') AS VALIDFROM, "
			+ "     DATE_FORMAT(MST_USER.VALIDTO,'%Y-%m-%d') AS VALIDTO "
			+ " FROM MST_USER "
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON MST_USER.COMPANYID = MST_COMPANY.COMPANYID "
			+ " INNER JOIN MST_ACCESSTYPE "
			+ "     ON MST_USER.ACCESSTYPEID = MST_ACCESSTYPE.ACCESSTYPEID "
			+ " WHERE MST_USER.USEREMAIL = ? ";

	/* Search records in User table by Reset Password Key */
	public static String SELECTSQL_USER_005 = "SELECT "
			+ "		MST_USER.USERID AS USERID, "
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ " 	MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	MST_USER.USERPASSWORD AS USERPASSWORD, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_USER.USEREMAIL AS USEREMAIL, " 
			+ " 	MST_ACCESSTYPE.ACCESSTYPECODE AS ACCESSTYPECODE, "
			+ "     DATE_FORMAT(MST_USER.VALIDFROM,'%Y-%m-%d') AS VALIDFROM, "
			+ "     DATE_FORMAT(MST_USER.VALIDTO,'%Y-%m-%d') AS VALIDTO "
			+ " FROM MST_USER "
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON MST_USER.COMPANYID = MST_COMPANY.COMPANYID "
			+ " INNER JOIN MST_ACCESSTYPE "
			+ "     ON MST_USER.ACCESSTYPEID = MST_ACCESSTYPE.ACCESSTYPEID "
			+ " WHERE MST_USER.RESETPASSWORDKEY = ? ";
	
	/* Search records in User table where Project members are not existing */
	public static String SELECTSQL_USER_006 = "SELECT  "
			+ "		MST_USER.USERID AS USERID, "
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ " 	MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	MST_USER.USERPASSWORD AS USERPASSWORD, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_USER.USEREMAIL AS USEREMAIL, " 
			+ " 	MST_ACCESSTYPE.ACCESSTYPECODE AS ACCESSTYPECODE, "
			+ "     DATE_FORMAT(MST_USER.VALIDFROM,'%Y-%m-%d') AS VALIDFROM, "
			+ "     DATE_FORMAT(MST_USER.VALIDTO,'%Y-%m-%d') AS VALIDTO "
			+ " FROM MST_USER "
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON MST_USER.COMPANYID = MST_COMPANY.COMPANYID "
			+ " INNER JOIN MST_ACCESSTYPE "
			+ "     ON MST_USER.ACCESSTYPEID = MST_ACCESSTYPE.ACCESSTYPEID "
			+ " WHERE NOT EXISTS "
			+ "     ( SELECT NULL "
			+ "       FROM WFG_PROJECTMEMBER "
			+ "       WHERE  WFG_PROJECTMEMBER.USERID = MST_USER.USERID AND"
			+ "             WFG_PROJECTMEMBER.PROJECTID = ? "
			+ "     ) ";
	
	/* Search records in User table by access type */
	public static String SELECTSQL_USER_007 = "SELECT "
			+ "		MST_USER.USERID AS USERID, "
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ " 	MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	MST_USER.USERPASSWORD AS USERPASSWORD, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_USER.USEREMAIL AS USEREMAIL, " 
			+ " 	MST_ACCESSTYPE.ACCESSTYPECODE AS ACCESSTYPECODE, "
			+ "     DATE_FORMAT(MST_USER.VALIDFROM,'%Y-%m-%d') AS VALIDFROM, "
			+ "     DATE_FORMAT(MST_USER.VALIDTO,'%Y-%m-%d') AS VALIDTO "
			+ " FROM MST_USER "
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON MST_USER.COMPANYID = MST_COMPANY.COMPANYID "
			+ " INNER JOIN MST_ACCESSTYPE "
			+ "     ON MST_USER.ACCESSTYPEID = MST_ACCESSTYPE.ACCESSTYPEID "
			+ " INNER JOIN MST_ACCESSTYPEDETAIL "
			+ "     ON MST_ACCESSTYPE.ACCESSTYPEID = MST_ACCESSTYPEDETAIL.ACCESSTYPEID "
			+ " INNER JOIN MST_PROGRAM "
			+ "      ON MST_ACCESSTYPEDETAIL.PROGRAMID = MST_PROGRAM.PROGRAMID "
			+ " WHERE MST_ACCESSTYPEDETAIL.ACCESSRIGHT != 'R' AND "
			+ "		MST_ACCESSTYPEDETAIL.ACCESSRIGHT != 'N' AND "
			+ "		MST_PROGRAM.JAVASERVLETREFERENCE = 'DashboardRequestViewServlet' ";

	/* Search records in Program table that are not yet selected for Edit mode */
	public static String SELECTSQL_USER_006_ADD01 = " OR MST_USER.USERNAME = ? ";

	/* Search all records in Vocabulary table */
	public static String SELECTSQL_VOCABULARY_001 = "SELECT * FROM MST_VOCABULARY ORDER BY VOCABID ";

	/* Search records in Vocabulary table by Vocabulary ID */
	public static String SELECTSQL_VOCABULARY_002 = "SELECT * FROM MST_VOCABULARY WHERE VOCABID = ? ";

	/* Search records in Vocabulary table by Vocabulary Name */
	public static String SELECTSQL_VOCABULARY_003 = "SELECT * FROM MST_VOCABULARY WHERE VOCABNAME = ? ";

	/*
	 * Search all records in Vocabulary Category table except for a specific
	 * entry
	 */
	public static String SELECTSQL_VOCABULARY_CATEGORY_001 = "SELECT * "
			+ " FROM MST_VOCABULARYCATEGORY " + " WHERE VOCABCATEGORYID != ? "
			+ " ORDER BY VOCABCATEGORYID ";

	/* Search records in Vocabulary Category table by Vocabulary ID */
	public static String SELECTSQL_VOCABULARY_CATEGORY_002 = "SELECT "
			+ " 	VOCABCATEGORYID, " 
			+ " 	VOCABCATEGORYNAME, "
			+ " 	VOCABCATEGORYPARENTID, " 
			+ " 	VOCABCATEGORYDESC "
			+ " FROM MST_VOCABULARYCATEGORY " 
			+ " WHERE VOCABCATEGORYID = ? ";

	/* Search records in Vocabulary Category table by Vocabulary Category Name */
	public static String SELECTSQL_VOCABULARY_CATEGORY_003 = "SELECT * "
			+ " FROM MST_VOCABULARYCATEGORY " + " WHERE VOCABCATEGORYNAME = ? ";

	/* Search all records in Vocabulary Category table */
	public static String SELECTSQL_VOCABULARY_CATEGORY_004 = "SELECT * "
			+ " FROM MST_VOCABULARYCATEGORY "
			+ " ORDER BY VOCABCATEGORYID ";

	/* Search all records in Project table */
	public static String SELECTSQL_PROJECT_001 = "SELECT "
			+ "		WFG_PROJECT.PROJECTID AS PROJECTID, "
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME, "
			+ " 	WFG_PROJECT.PROJECTDESCRIPTION AS PROJECTDESCRIPTION, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_COMPANY.COMPANYNAME AS COMPANYNAME, "
			+ " 	WFG_PROJECT.PROJECTSTATUS AS PROJECTSTATUS, "
			+ "     DATE_FORMAT(WFG_PROJECT.PROJECTSTARTDATE,'%Y-%m-%d') AS PROJECTSTARTDATE "
			+ " FROM WFG_PROJECT " 
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON WFG_PROJECT.COMPANYID = MST_COMPANY.COMPANYID ";

	/* Search records in Project table by Project ID */
	public static String SELECTSQL_PROJECT_002 = "SELECT "
			+ "		WFG_PROJECT.PROJECTID AS PROJECTID, "
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME, "
			+ " 	WFG_PROJECT.PROJECTDESCRIPTION AS PROJECTDESCRIPTION, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_COMPANY.COMPANYNAME AS COMPANYNAME, "
			+ " 	WFG_PROJECT.PROJECTSTATUS AS PROJECTSTATUS, "	
			+ "     DATE_FORMAT(WFG_PROJECT.PROJECTSTARTDATE,'%Y-%m-%d') AS PROJECTSTARTDATE "
			+ " FROM WFG_PROJECT " 
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON WFG_PROJECT.COMPANYID = MST_COMPANY.COMPANYID "
			+ " WHERE WFG_PROJECT.PROJECTID = ? ";

	/* Search records in Project table by Project Name */
	public static String SELECTSQL_PROJECT_003 = "SELECT "
			+ "		WFG_PROJECT.PROJECTID AS PROJECTID, "
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME, "
			+ " 	WFG_PROJECT.PROJECTDESCRIPTION AS PROJECTDESCRIPTION, "
			+ " 	MST_COMPANY.COMPANYCODE AS COMPANYCODE, "
			+ " 	MST_COMPANY.COMPANYNAME AS COMPANYNAME, "
			+ " 	WFG_PROJECT.PROJECTSTATUS AS PROJECTSTATUS, "
			+ "     DATE_FORMAT(WFG_PROJECT.PROJECTSTARTDATE,'%Y-%m-%d') AS PROJECTSTARTDATE "
			+ " FROM WFG_PROJECT " 
			+ " INNER JOIN MST_COMPANY "
			+ " 	ON WFG_PROJECT.COMPANYID = MST_COMPANY.COMPANYID "
			+ " WHERE WFG_PROJECT.PROJECTNAME = ? ";

	/* Search all records in Task table */
	public static String SELECTSQL_TASK_001 = "SELECT "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASK.TASKNAME AS TASKNAME, "
			+ " 	WFG_TASK.TASKWORKPOINTS AS TASKWORKPOINTS, "
			+ " 	WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS, "
			+ " 	WFG_TASK.TASKPROGRESS AS TASKPROGRESS, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKDEADLINE,'%Y-%m-%d') AS TASKDEADLINE, "
			+ " 	WFG_TASK.TASKPLANINFOPLANNEDHOURS AS TASKPLANINFOPLANNEDHOURS, "
			+ " 	WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOSTARTDATE,'%Y-%m-%d') AS TASKPLANINFOSTARTDATE, " 
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOENDDATE,'%Y-%m-%d') AS TASKPLANINFOENDDATE, " 
			+ " 	WFG_TASK.TASKPLANINFOCOMMENT AS TASKPLANINFOCOMMENT, " 
			+ " 	WFG_TASK.TASKACTIVITYINFOSTATUS AS TASKACTIVITYINFOSTATUS "
			+ " FROM WFG_TASK "
			+ " INNER JOIN WFG_WORKFLOW "
			+ " 	ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " WHERE WFG_WORKFLOW.WORKFLOWID = ? ";

	/* Search all Prerequisite Tasks in Task table */
	public static String SELECTSQL_TASK_002 = "SELECT "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASK.TASKNAME AS TASKNAME, "
			+ " 	WFG_TASK.TASKWORKPOINTS AS TASKWORKPOINTS, "
			+ " 	WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS, "
			+ " 	WFG_TASK.TASKPROGRESS AS TASKPROGRESS, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKDEADLINE,'%Y-%m-%d') AS TASKDEADLINE, "
			+ " 	WFG_TASK.TASKPLANINFOPLANNEDHOURS AS TASKPLANINFOPLANNEDHOURS, "
			+ " 	WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOSTARTDATE,'%Y-%m-%d') AS TASKPLANINFOSTARTDATE, " 
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOENDDATE,'%Y-%m-%d') AS TASKPLANINFOENDDATE, " 
			+ " 	WFG_TASK.TASKPLANINFOCOMMENT AS TASKPLANINFOCOMMENT, "
			+ " 	WFG_TASK.TASKACTIVITYINFOSTATUS AS TASKACTIVITYINFOSTATUS "
			+ " FROM WFG_TASK "
			+ " INNER JOIN WFG_WORKFLOW "
			+ " 	ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " WHERE WFG_WORKFLOW.WORKFLOWID = ? AND "
			+ " 	WFG_TASK.TASKID != ? ";

	/* Search a record in Task table by Task ID */
	public static String SELECTSQL_TASK_003 = "SELECT "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASK.TASKNAME AS TASKNAME, "
			+ " 	WFG_TASK.TASKWORKPOINTS AS TASKWORKPOINTS, "
			+ " 	WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS, "
			+ " 	WFG_TASK.TASKPROGRESS AS TASKPROGRESS, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKDEADLINE,'%Y-%m-%d') AS TASKDEADLINE, "
			+ " 	WFG_TASK.TASKPLANINFOPLANNEDHOURS AS TASKPLANINFOPLANNEDHOURS, "
			+ " 	WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOSTARTDATE,'%Y-%m-%d') AS TASKPLANINFOSTARTDATE, " 
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOENDDATE,'%Y-%m-%d') AS TASKPLANINFOENDDATE, " 
			+ " 	WFG_TASK.TASKPLANINFOCOMMENT AS TASKPLANINFOCOMMENT, " 
			+ " 	WFG_TASK.TASKACTIVITYINFOSTATUS AS TASKACTIVITYINFOSTATUS "
			+ " FROM WFG_TASK "
			+ " INNER JOIN WFG_WORKFLOW "
			+ " 	ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " WHERE WFG_TASK.TASKID = ? ";
	
	/* Search records For daily Tasks in Task table by TaskAssigned User ID */
	public static String SELECTSQL_TASK_004 = "SELECT "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASK.TASKNAME AS TASKNAME, "
			+ "     WFG_PROJECT.PROJECTNAME AS PROJECTNAME,"
			+ " 	WFG_TASK.TASKWORKPOINTS AS TASKWORKPOINTS, "
			+ " 	WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS, "
			+ " 	WFG_TASK.TASKPROGRESS AS TASKPROGRESS, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKDEADLINE,'%Y-%m-%d') AS TASKDEADLINE, "
			+ " 	WFG_TASK.TASKPLANINFOPLANNEDHOURS AS TASKPLANINFOPLANNEDHOURS, "
			+ " 	WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOSTARTDATE,'%Y-%m-%d') AS TASKPLANINFOSTARTDATE, " 
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOENDDATE,'%Y-%m-%d') AS TASKPLANINFOENDDATE, " 
			+ " 	WFG_TASK.TASKPLANINFOCOMMENT AS TASKPLANINFOCOMMENT, " 
			+ " 	WFG_TASK.TASKACTIVITYINFOSTATUS AS TASKACTIVITYINFOSTATUS, "
			+ "     WFG_TASKASSIGNEDUSER.USERID AS USERID, "
			+ "     MST_PHASE.PHASECODE AS PHASECODE "
			+ " FROM WFG_TASK "
			+ " INNER JOIN WFG_TASKASSIGNEDUSER" 
			+ "		ON WFG_TASKASSIGNEDUSER.TASKID = WFG_TASK.TASKID"
			+ " INNER JOIN WFG_WORKFLOW "
			+ " 	ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
 			+ " INNER JOIN MST_PHASE  "
			+ "		ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID" 
			+ " WHERE ((WFG_TASKASSIGNEDUSER.USERID = ? ) "
			+ "	   	AND ((DATE_FORMAT(WFG_TASK.TASKPLANINFOSTARTDATE,'%Y-%m-%d') = cast(now() as date)) "
			+ "		AND ((WFG_TASK.TASKACTIVITYINFOSTATUS = ? ) OR "
			+ "		(WFG_TASK.TASKACTIVITYINFOSTATUS = ? ) OR "
			+ "		(WFG_TASK.TASKACTIVITYINFOSTATUS = ? )))) " ;
	
	/* Search records for Weekly Task in Task table by task Assigned User ID */
	public static String SELECTSQL_TASK_005 = "SELECT "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASK.TASKNAME AS TASKNAME, "
			+ "     WFG_PROJECT.PROJECTNAME AS PROJECTNAME,"
			+ " 	WFG_TASK.TASKWORKPOINTS AS TASKWORKPOINTS, "
			+ " 	WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS, "
			+ " 	WFG_TASK.TASKPROGRESS AS TASKPROGRESS, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKDEADLINE,'%Y-%m-%d') AS TASKDEADLINE, "
			+ " 	WFG_TASK.TASKPLANINFOPLANNEDHOURS AS TASKPLANINFOPLANNEDHOURS, "
			+ " 	WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOSTARTDATE,'%Y-%m-%d') AS TASKPLANINFOSTARTDATE, " 
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOENDDATE,'%Y-%m-%d') AS TASKPLANINFOENDDATE, " 
			+ " 	WFG_TASK.TASKPLANINFOCOMMENT AS TASKPLANINFOCOMMENT, " 
			+ " 	WFG_TASK.TASKACTIVITYINFOSTATUS AS TASKACTIVITYINFOSTATUS, "
			+ "     WFG_TASKASSIGNEDUSER.USERID AS USERID, "
			+ "     MST_PHASE.PHASECODE AS PHASECODE "
			+ " FROM WFG_TASK "
			+ " INNER JOIN WFG_TASKASSIGNEDUSER" 
			+ "		ON WFG_TASKASSIGNEDUSER.TASKID = WFG_TASK.TASKID"
			+ " INNER JOIN WFG_WORKFLOW "
			+ " 	ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
 			+ " INNER JOIN MST_PHASE  "
			+ "		ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID" 
			+ " WHERE (WFG_TASKASSIGNEDUSER.USERID = ? "
			+ "		AND ((TASKPLANINFOSTARTDATE >= (DATE_SUB(CURDATE(), INTERVAL DAYOFWEEK(CURDATE()) -1 DAY)))"
			+ "		AND (TASKPLANINFOSTARTDATE <= (DATE_SUB(CURDATE(), INTERVAL DAYOFWEEK(CURDATE()) -7 DAY )))) "
			+ "		OR ((TASKPLANINFOENDDATE >= (DATE_SUB(CURDATE(), INTERVAL DAYOFWEEK(CURDATE()) -1 DAY)))"
			+ "		AND (TASKPLANINFOENDDATE <= (DATE_SUB(CURDATE(), INTERVAL DAYOFWEEK(CURDATE()) -7 DAY )))) "
			+ "		AND ((WFG_TASK.TASKACTIVITYINFOSTATUS = ? ) OR "
			+ "		(WFG_TASK.TASKACTIVITYINFOSTATUS = ? ) OR "
			+ "		(WFG_TASK.TASKACTIVITYINFOSTATUS = ? ))) " ;
	
	/* Search all record in Task table by Task Assigned User ID */
	public static String SELECTSQL_TASK_006 = "SELECT "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASK.TASKNAME AS TASKNAME, "
			+ "     WFG_PROJECT.PROJECTNAME AS PROJECTNAME,"
			+ " 	WFG_TASK.TASKWORKPOINTS AS TASKWORKPOINTS, "
			+ " 	WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS, "
			+ " 	WFG_TASK.TASKPROGRESS AS TASKPROGRESS, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKDEADLINE,'%Y-%m-%d') AS TASKDEADLINE, "
			+ " 	WFG_TASK.TASKPLANINFOPLANNEDHOURS AS TASKPLANINFOPLANNEDHOURS, "
			+ " 	WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOSTARTDATE,'%Y-%m-%d') AS TASKPLANINFOSTARTDATE, " 
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOENDDATE,'%Y-%m-%d') AS TASKPLANINFOENDDATE, " 
			+ " 	WFG_TASK.TASKPLANINFOCOMMENT AS TASKPLANINFOCOMMENT, " 
			+ " 	WFG_TASK.TASKACTIVITYINFOSTATUS AS TASKACTIVITYINFOSTATUS, "
			+ "     WFG_TASKASSIGNEDUSER.USERID AS USERID, "
			+ "     MST_PHASE.PHASECODE AS PHASECODE "
			+ " FROM WFG_TASK "
			+ " INNER JOIN WFG_TASKASSIGNEDUSER" 
			+ "		ON WFG_TASKASSIGNEDUSER.TASKID = WFG_TASK.TASKID"
			+ " INNER JOIN WFG_WORKFLOW "
			+ " 	ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
 			+ " INNER JOIN MST_PHASE  "
			+ "		ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID" 
			+ " WHERE WFG_TASKASSIGNEDUSER.USERID = ? ";
	
	/* Search records for pending Tasks in Task table by task Assigned User ID */
	public static String SELECTSQL_TASK_007 = "SELECT "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASK.TASKNAME AS TASKNAME, "
			+ "     WFG_PROJECT.PROJECTNAME AS PROJECTNAME,"
			+ " 	WFG_TASK.TASKWORKPOINTS AS TASKWORKPOINTS, "
			+ " 	WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS, "
			+ " 	WFG_TASK.TASKPROGRESS AS TASKPROGRESS, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKDEADLINE,'%Y-%m-%d') AS TASKDEADLINE, "
			+ " 	WFG_TASK.TASKPLANINFOPLANNEDHOURS AS TASKPLANINFOPLANNEDHOURS, "
			+ " 	WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOSTARTDATE,'%Y-%m-%d') AS TASKPLANINFOSTARTDATE, " 
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOENDDATE,'%Y-%m-%d') AS TASKPLANINFOENDDATE, " 
			+ " 	WFG_TASK.TASKPLANINFOCOMMENT AS TASKPLANINFOCOMMENT, " 
			+ " 	WFG_TASK.TASKACTIVITYINFOSTATUS AS TASKACTIVITYINFOSTATUS, "
			+ "     WFG_TASKASSIGNEDUSER.USERID AS USERID, "
			+ "     MST_PHASE.PHASECODE AS PHASECODE "
			+ " FROM WFG_TASK "
			+ " INNER JOIN WFG_TASKASSIGNEDUSER" 
			+ "		ON WFG_TASKASSIGNEDUSER.TASKID = WFG_TASK.TASKID"
			+ " INNER JOIN WFG_WORKFLOW "
			+ " 	ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
 			+ " INNER JOIN MST_PHASE  "
			+ "		ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID" 
			+ " WHERE WFG_TASKASSIGNEDUSER.USERID = ? "
			+ " AND  (WFG_TASK.TASKACTIVITYINFOSTATUS = ? "
			+ "  OR	WFG_TASK.TASKACTIVITYINFOSTATUS = ? "
			+ " OR	WFG_TASK.TASKACTIVITYINFOSTATUS = ? "
			+ "	  OR	WFG_TASK.TASKACTIVITYINFOSTATUS = ? )"
			+ "AND ((DATE_FORMAT(WFG_TASK.TASKDEADLINE,'%Y-%m-%d') < cast(now() as date))) ";
	
	/* Search all records in Task table by Project ID */
	public static String SELECTSQL_TASK_008 = "SELECT "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASK.TASKNAME AS TASKNAME, "
			+ " 	WFG_TASK.TASKWORKPOINTS AS TASKWORKPOINTS, "
			+ " 	WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS, "
			+ " 	WFG_TASK.TASKPROGRESS AS TASKPROGRESS, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKDEADLINE,'%Y-%m-%d') AS TASKDEADLINE, "
			+ " 	WFG_TASK.TASKPLANINFOPLANNEDHOURS AS TASKPLANINFOPLANNEDHOURS, "
			+ " 	WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY, "
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOSTARTDATE,'%Y-%m-%d') AS TASKPLANINFOSTARTDATE, " 
			+ " 	DATE_FORMAT(WFG_TASK.TASKPLANINFOENDDATE,'%Y-%m-%d') AS TASKPLANINFOENDDATE, " 
			+ " 	WFG_TASK.TASKPLANINFOCOMMENT AS TASKPLANINFOCOMMENT, " 
			+ " 	WFG_TASK.TASKACTIVITYINFOSTATUS AS TASKACTIVITYINFOSTATUS "
			+ " FROM WFG_TASK "
			+ " INNER JOIN WFG_WORKFLOW "
			+ " 	ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " WHERE WFG_PROJECT.PROJECTID = ? ";
	
	/* Search all records in Task Checkpoint table by Task Document Id */
	public static String SELECTSQL_TASK_CHECKPOINT_001 = "SELECT "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ "		WFG_TASKCHECKPOINT.TASKCHECKPOINTID AS TASKCHECKPOINTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTNAME AS TASKCHECKPOINTNAME, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTDESCRIPTION AS TASKCHECKPOINTDESCRIPTION "
			+ " FROM WFG_TASKCHECKPOINT "
			+ " INNER JOIN WFG_TASKDOCUMENT "
			+ " 	ON WFG_TASKCHECKPOINT.TASKDOCUMENTID = WFG_TASKDOCUMENT.TASKDOCUMENTID "
			+ "	INNER JOIN "
			+ "		WFG_TASK ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN "
			+ " 	WFG_WORKFLOW ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_TASKDOCUMENT.TASKDOCUMENTID = ? ";

	/* Search all records in Task Checkpoint table by Task Checkpoint ID */
	public static String SELECTSQL_TASK_CHECKPOINT_002 = "SELECT "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ "		WFG_TASKCHECKPOINT.TASKCHECKPOINTID AS TASKCHECKPOINTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTNAME AS TASKCHECKPOINTNAME, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTDESCRIPTION AS TASKCHECKPOINTDESCRIPTION "
			+ " FROM WFG_TASKCHECKPOINT "
			+ "	INNER JOIN WFG_TASKDOCUMENT "
			+ " 	ON WFG_TASKCHECKPOINT.TASKDOCUMENTID = WFG_TASKDOCUMENT.TASKDOCUMENTID "
			+ "	INNER JOIN "
			+ "		WFG_TASK ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN "
			+ "		WFG_WORKFLOW ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_TASKCHECKPOINT.TASKCHECKPOINTID = ? ";
	
	/* Search all records in Task Checkpoint table by Task Id */
	public static String SELECTSQL_TASK_CHECKPOINT_003 = "SELECT "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ "		WFG_TASKCHECKPOINT.TASKCHECKPOINTID AS TASKCHECKPOINTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTNAME AS TASKCHECKPOINTNAME, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTDESCRIPTION AS TASKCHECKPOINTDESCRIPTION "
			+ " FROM WFG_TASKCHECKPOINT "
			+ " INNER JOIN WFG_TASKDOCUMENT "
			+ " 	ON WFG_TASKCHECKPOINT.TASKDOCUMENTID = WFG_TASKDOCUMENT.TASKDOCUMENTID "
			+ "	INNER JOIN "
			+ "		WFG_TASK ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN "
			+ " 	WFG_WORKFLOW ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_TASK.TASKID  = ? ";
	
	/* Search all records in Task Checkpoint table by Workflow Id */
	public static String SELECTSQL_TASK_CHECKPOINT_004 = "SELECT "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ "		WFG_TASKCHECKPOINT.TASKCHECKPOINTID AS TASKCHECKPOINTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTNAME AS TASKCHECKPOINTNAME, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTDESCRIPTION AS TASKCHECKPOINTDESCRIPTION "
			+ " FROM WFG_TASKCHECKPOINT "
			+ " INNER JOIN WFG_TASKDOCUMENT "
			+ " 	ON WFG_TASKCHECKPOINT.TASKDOCUMENTID = WFG_TASKDOCUMENT.TASKDOCUMENTID "
			+ "	INNER JOIN "
			+ "		WFG_TASK ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN "
			+ "		 WFG_WORKFLOW ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_WORKFLOW.WORKFLOWID = ? ";
	
	/* Search all records in Task Checkpoint table by Project Id */
	public static String SELECTSQL_TASK_CHECKPOINT_005 = "SELECT "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ "		WFG_TASKCHECKPOINT.TASKCHECKPOINTID AS TASKCHECKPOINTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTNAME AS TASKCHECKPOINTNAME, "
			+ " 	WFG_TASKCHECKPOINT.TASKCHECKPOINTDESCRIPTION AS TASKCHECKPOINTDESCRIPTION "
			+ " FROM WFG_TASKCHECKPOINT "
			+ " INNER JOIN WFG_TASKDOCUMENT "
			+ " 	ON WFG_TASKCHECKPOINT.TASKDOCUMENTID = WFG_TASKDOCUMENT.TASKDOCUMENTID "
			+ "	INNER JOIN "
			+ "		WFG_TASK ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN "
			+ "		 WFG_WORKFLOW ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ " 	ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " WHERE WFG_PROJECT.PROJECTID = ? ";

	/* Search all records in Task Document table */
	public static String SELECTSQL_TASK_DOCUMENT_001 = "SELECT "
			+ "		WFG_TASKDOCUMENT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTINPUTOUTPUT AS TASKDOCUMENTINPUTOUTPUT, "
			+ " 	WFG_TASKDOCUMENT.DOCUMENTTYPEID AS DOCUMENTTYPEID, "
			+ " 	MST_DOCUMENTTYPE.DOCUMENTTYPECODE AS DOCUMENTTYPECODE, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTNAME AS TASKDOCUMENTNAME, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTPATH AS TASKDOCUMENTPATH "
			+ " FROM WFG_TASKDOCUMENT "
			+ " INNER JOIN MST_DOCUMENTTYPE "
			+ " 	ON WFG_TASKDOCUMENT.DOCUMENTTYPEID = MST_DOCUMENTTYPE.DOCUMENTTYPEID "
			+ "	INNER JOIN WFG_TASK"
			+ "		ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW"
			+ "     ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_TASKDOCUMENT.TASKID = ? AND "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTINPUTOUTPUT = ? ";

	/* Search a record in Task Document table by Task Document ID */
	public static String SELECTSQL_TASK_DOCUMENT_002 = "SELECT "
			+ "		WFG_TASKDOCUMENT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTINPUTOUTPUT AS TASKDOCUMENTINPUTOUTPUT, "
			+ " 	WFG_TASKDOCUMENT.DOCUMENTTYPEID AS DOCUMENTTYPEID, "
			+ " 	MST_DOCUMENTTYPE.DOCUMENTTYPECODE AS DOCUMENTTYPECODE, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTNAME AS TASKDOCUMENTNAME, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTPATH AS TASKDOCUMENTPATH "
			+ " FROM WFG_TASKDOCUMENT "
			+ " INNER JOIN MST_DOCUMENTTYPE "
			+ " 	ON WFG_TASKDOCUMENT.DOCUMENTTYPEID = MST_DOCUMENTTYPE.DOCUMENTTYPEID "
			+ "	INNER JOIN WFG_TASK"
			+ "		ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW"
			+ "     ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_TASKDOCUMENT.TASKDOCUMENTID = ? ";

	/* Search Document File in Task Document table by Task Document ID */
	public static String SELECTSQL_TASK_DOCUMENT_003 = "SELECT "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTFILE AS TASKDOCUMENTFILE "
			+ " FROM WFG_TASKDOCUMENT "
			+ " WHERE WFG_TASKDOCUMENT.TASKDOCUMENTID = ? ";

	/* Search all records in Task Document table */
	public static String SELECTSQL_TASK_DOCUMENT_004 = "SELECT "
			+ "		WFG_TASKDOCUMENT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ "		WFG_TASKDOCUMENT.DOCUMENTTYPEID AS DOCUMENTTYPEID, "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTINPUTOUTPUT AS TASKDOCUMENTINPUTOUTPUT, "
			+ " 	MST_DOCUMENTTYPE.DOCUMENTTYPECODE AS DOCUMENTTYPECODE, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTNAME AS TASKDOCUMENTNAME, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTPATH AS TASKDOCUMENTPATH "
			+ " FROM WFG_TASKDOCUMENT "
			+ " INNER JOIN MST_DOCUMENTTYPE "
			+ " 	ON WFG_TASKDOCUMENT.DOCUMENTTYPEID = MST_DOCUMENTTYPE.DOCUMENTTYPEID "
			+ "	INNER JOIN WFG_TASK"
			+ "		ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW"
			+ "     ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_TASKDOCUMENT.TASKID = ? ";
	
	/* Search all records in Task Document table by Workflow ID */
	public static String SELECTSQL_TASK_DOCUMENT_005 = "SELECT "
			+ "		WFG_TASKDOCUMENT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ "		WFG_TASKDOCUMENT.DOCUMENTTYPEID AS DOCUMENTTYPEID, "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTINPUTOUTPUT AS TASKDOCUMENTINPUTOUTPUT, "
			+ " 	MST_DOCUMENTTYPE.DOCUMENTTYPECODE AS DOCUMENTTYPECODE, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTNAME AS TASKDOCUMENTNAME, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTPATH AS TASKDOCUMENTPATH "
			+ " FROM WFG_TASKDOCUMENT "
			+ " INNER JOIN MST_DOCUMENTTYPE "
			+ " 	ON WFG_TASKDOCUMENT.DOCUMENTTYPEID = MST_DOCUMENTTYPE.DOCUMENTTYPEID "
			+ "	INNER JOIN WFG_TASK"
			+ "		ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW"
			+ "     ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_WORKFLOW.WORKFLOWID = ? ";
	
	/* Search all records in Task Document table by Workflow ID */
	public static String SELECTSQL_TASK_DOCUMENT_006 = "SELECT "
			+ "		WFG_TASKDOCUMENT.TASKDOCUMENTID AS TASKDOCUMENTID, "
			+ "		WFG_TASKDOCUMENT.DOCUMENTTYPEID AS DOCUMENTTYPEID, "
			+ " 	WFG_TASKDOCUMENT.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTINPUTOUTPUT AS TASKDOCUMENTINPUTOUTPUT, "
			+ " 	MST_DOCUMENTTYPE.DOCUMENTTYPECODE AS DOCUMENTTYPECODE, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTNAME AS TASKDOCUMENTNAME, "
			+ " 	WFG_TASKDOCUMENT.TASKDOCUMENTPATH AS TASKDOCUMENTPATH "
			+ " FROM WFG_TASKDOCUMENT "
			+ " INNER JOIN MST_DOCUMENTTYPE "
			+ " 	ON WFG_TASKDOCUMENT.DOCUMENTTYPEID = MST_DOCUMENTTYPE.DOCUMENTTYPEID "
			+ "	INNER JOIN WFG_TASK"
			+ "		ON WFG_TASKDOCUMENT.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW"
			+ "     ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ " 	ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " WHERE WFG_PROJECT.PROJECTID = ? ";

	/* Search all records in Task Prerequisite table by Task ID Parent */
	public static String SELECTSQL_TASK_PREREQUISITE_001 = "SELECT "
			+ " 	WFG_TASKPREREQ.TASKPREREQID AS TASKPREREQID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_TASKPREREQ.TASKIDPARENT AS TASKIDPARENT, "
			+ " 	WFG_TASKPREREQ.TASKIDCHILD AS TASKIDCHILD, "
			+ " 	WFG_TASK.TASKNAME AS TASKNAME " 
			+ " FROM WFG_TASKPREREQ "
			+ " INNER JOIN WFG_TASK "
			+ " 	ON WFG_TASKPREREQ.TASKIDCHILD = WFG_TASK.TASKID "
			+ " WHERE WFG_TASKPREREQ.TASKIDPARENT = ? ";

	/* Search a record in Task Prerequisite table by Task Prerequisite ID */
	public static String SELECTSQL_TASK_PREREQUISITE_002 = "SELECT "
			+ "     WFG_TASKPREREQ.TASKPREREQID AS TASKPREREQID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ "     WFG_TASKPREREQ.TASKIDPARENT AS TASKIDPARENT, "
			+ "     WFG_TASKPREREQ.TASKIDCHILD AS TASKIDCHILD, "
			+ "     WFG_TASK.TASKNAME AS TASKNAME " 
			+ " FROM WFG_TASKPREREQ "
			+ " INNER JOIN WFG_TASK "
			+ "     ON WFG_TASKPREREQ.TASKIDCHILD = WFG_TASK.TASKID "
			+ " WHERE WFG_TASKPREREQ.TASKPREREQID = ? ";
	
	/* Search a record in Task Prerequisite table by Workflow ID */
	public static String SELECTSQL_TASK_PREREQUISITE_003 = "SELECT "
			+ "     WFG_TASKPREREQ.TASKPREREQID AS TASKPREREQID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ "     WFG_TASKPREREQ.TASKIDPARENT AS TASKIDPARENT, "
			+ "     WFG_TASKPREREQ.TASKIDCHILD AS TASKIDCHILD, "
			+ "     WFG_TASK.TASKNAME AS TASKNAME " 
			+ " FROM WFG_TASKPREREQ "
			+ " INNER JOIN WFG_TASK "
			+ "     ON WFG_TASKPREREQ.TASKIDCHILD = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW"
			+ "     ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_WORKFLOW.WORKFLOWID  = ? ";
	
	/* Search a record in Task Prerequisite table by Project ID */
	public static String SELECTSQL_TASK_PREREQUISITE_004 = "SELECT "
			+ "     WFG_TASKPREREQ.TASKPREREQID AS TASKPREREQID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ "     WFG_TASKPREREQ.TASKIDPARENT AS TASKIDPARENT, "
			+ "     WFG_TASKPREREQ.TASKIDCHILD AS TASKIDCHILD, "
			+ "     WFG_TASK.TASKNAME AS TASKNAME " 
			+ " FROM WFG_TASKPREREQ "
			+ " INNER JOIN WFG_TASK "
			+ "     ON WFG_TASKPREREQ.TASKIDCHILD = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW"
			+ "     ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " WHERE WFG_PROJECT.PROJECTID  = ? ";

	/* Search all records in Task Assigned User table */
	public static String SELECTSQL_TASK_ASSIGNEDUSER_001 = "SELECT "
			+ "		WFG_TASKASSIGNEDUSER.TASKASSIGNEDUSERID AS TASKASSIGNEDUSERID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASKASSIGNEDUSER.USERID AS USERID,"
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ "		WFG_TASK.TASKNAME AS TASKNAME,"
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME,"
			+ "		WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS,"
			+ "		WFG_TASK.TASKPROGRESS AS TASKPROGRESS,"
			+ "		WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY,"
			+ "		MST_PHASE.PHASECODE AS PHASECODE"
			+ " FROM WFG_TASKASSIGNEDUSER "
			+ " INNER JOIN MST_USER "
			+ " 	ON WFG_TASKASSIGNEDUSER.USERID = MST_USER.USERID "
			+ " INNER JOIN WFG_TASK "
			+ " 	ON WFG_TASKASSIGNEDUSER.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW "
			+ "		ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " INNER JOIN MST_PHASE "
			+ "		ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID "	
			+ " WHERE WFG_TASK.TASKID = ? ";
	
	/* Search all records in Task Assigned User table by Task Assigned User ID */
	public static String SELECTSQL_TASK_ASSIGNEDUSER_002 = "SELECT "
			+ "		WFG_TASKASSIGNEDUSER.TASKASSIGNEDUSERID AS TASKASSIGNEDUSERID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASKASSIGNEDUSER.USERID AS USERID,"
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ "		WFG_TASK.TASKNAME AS TASKNAME,"
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME,"
			+ "		WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS,"
			+ "		WFG_TASK.TASKPROGRESS AS TASKPROGRESS,"
			+ "		WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY,"
			+ "		MST_PHASE.PHASECODE AS PHASECODE"
			+ " FROM WFG_TASKASSIGNEDUSER "
			+ " INNER JOIN MST_USER "
			+ " 	ON WFG_TASKASSIGNEDUSER.USERID = MST_USER.USERID "
			+ " INNER JOIN WFG_TASK "
			+ " 	ON WFG_TASKASSIGNEDUSER.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW "
			+ "		ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " INNER JOIN MST_PHASE "
			+ "		ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID "
			+ " WHERE WFG_TASKASSIGNEDUSER.TASKASSIGNEDUSERID = ? ";
	
	/* Search all records in Task Assigned User table by Workflow ID */
	public static String SELECTSQL_TASK_ASSIGNEDUSER_003 = "SELECT "
			+ "		WFG_TASKASSIGNEDUSER.TASKASSIGNEDUSERID AS TASKASSIGNEDUSERID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASKASSIGNEDUSER.USERID AS USERID,"
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ "		WFG_TASK.TASKNAME AS TASKNAME,"
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME,"
			+ "		WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS,"
			+ "		WFG_TASK.TASKPROGRESS AS TASKPROGRESS,"
			+ "		WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY,"
			+ "		MST_PHASE.PHASECODE AS PHASECODE"
			+ " FROM WFG_TASKASSIGNEDUSER "
			+ " INNER JOIN MST_USER "
			+ " 	ON WFG_TASKASSIGNEDUSER.USERID = MST_USER.USERID "
			+ " INNER JOIN WFG_TASK "
			+ " 	ON WFG_TASKASSIGNEDUSER.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW "
			+ "		ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " INNER JOIN MST_PHASE "
			+ "		ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID "	
			+ " WHERE WFG_WORKFLOW.WORKFLOWID = ? ";
	
	/* Search all records in Task Assigned User table by Project ID */
	public static String SELECTSQL_TASK_ASSIGNEDUSER_004 = "SELECT "
			+ "		WFG_TASKASSIGNEDUSER.TASKASSIGNEDUSERID AS TASKASSIGNEDUSERID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ " 	WFG_TASKASSIGNEDUSER.USERID AS USERID,"
			+ " 	MST_USER.USERNAME AS USERNAME, "
			+ "		WFG_TASK.TASKNAME AS TASKNAME,"
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME,"
			+ "		WFG_TASK.TASKTOTALHOURS AS TASKTOTALHOURS,"
			+ "		WFG_TASK.TASKPROGRESS AS TASKPROGRESS,"
			+ "		WFG_TASK.TASKPLANINFOPRIORITY AS TASKPLANINFOPRIORITY,"
			+ "		MST_PHASE.PHASECODE AS PHASECODE"
			+ " FROM WFG_TASKASSIGNEDUSER "
			+ " INNER JOIN MST_USER "
			+ " 	ON WFG_TASKASSIGNEDUSER.USERID = MST_USER.USERID "
			+ " INNER JOIN WFG_TASK "
			+ " 	ON WFG_TASKASSIGNEDUSER.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW "
			+ "		ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ "		ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " INNER JOIN MST_PHASE "
			+ "		ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID "	
			+ " WHERE WFG_PROJECT.PROJECTID = ? ";
	
	/* Search all records in Task Detailed Task table by Task ID*/
	public static String SELECTSQL_TASK_DETAILEDTASK_001 = "SELECT "
			+ "		WFG_TASKDETAILEDTASK.TASKDETAILEDTASKID AS TASKDETAILEDTASKID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ "		MST_USER.USERID AS USERID, "
			+ "		MST_USER.USERNAME AS USERNAME, "
			+ "		WFG_TASKDETAILEDTASK.TASKDETAILEDTASKNAME AS TASKDETAILEDTASKNAME, "
			+ "		WFG_TASKDETAILEDTASK.TASKDETAILEDTASKHOURS AS TASKDETAILEDTASKHOURS, "
			+ "		DATE_FORMAT(WFG_TASKDETAILEDTASK.TASKDETAILEDTASKDATE, '%Y-%m-%d') AS TASKDETAILEDTASKDATE "
			+ " FROM WFG_TASKDETAILEDTASK "
			+ " INNER JOIN MST_USER "
			+ "		ON WFG_TASKDETAILEDTASK.ASSIGNEDUSERID =  MST_USER.USERID  "
			+ "	INNER JOIN WFG_TASK "
			+ "		ON WFG_TASKDETAILEDTASK.TASKID = WFG_TASK.TASKID "
			+ "	WHERE WFG_TASK.TASKID = ? ";
	
	/* Search all records in Task Detailed Task table by Workflow ID*/
	public static String SELECTSQL_TASK_DETAILEDTASK_002 = "SELECT "
			+ "		WFG_TASKDETAILEDTASK.TASKDETAILEDTASKID AS TASKDETAILEDTASKID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ "		WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ "		MST_USER.USERID AS USERID, "
			+ "		MST_USER.USERNAME AS USERNAME, "
			+ "		WFG_TASKDETAILEDTASK.TASKDETAILEDTASKNAME AS TASKDETAILEDTASKNAME, "
			+ "		WFG_TASKDETAILEDTASK.TASKDETAILEDTASKHOURS AS TASKDETAILEDTASKHOURS, "
			+ "		DATE_FORMAT(WFG_TASKDETAILEDTASK.TASKDETAILEDTASKDATE, '%Y-%m-%d') AS TASKDETAILEDTASKDATE "
			+ " FROM WFG_TASKDETAILEDTASK "
			+ " INNER JOIN MST_USER "
			+ "		ON WFG_TASKDETAILEDTASK.ASSIGNEDUSERID =  MST_USER.USERID  "
			+ "	INNER JOIN WFG_TASK "
			+ "		ON WFG_TASKDETAILEDTASK.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW"
			+ "     ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " WHERE WFG_WORKFLOW.WORKFLOWID = ? ";
	
	/* Search all records in Task Detailed Task table by Workflow ID*/
	public static String SELECTSQL_TASK_DETAILEDTASK_003 = "SELECT "
			+ "		WFG_TASKDETAILEDTASK.TASKDETAILEDTASKID AS TASKDETAILEDTASKID, "
			+ "		WFG_TASK.TASKID AS TASKID, "
			+ "		WFG_TASK.WORKFLOWID AS WORKFLOWID, "
			+ "		MST_USER.USERID AS USERID, "
			+ "		MST_USER.USERNAME AS USERNAME, "
			+ "		WFG_TASKDETAILEDTASK.TASKDETAILEDTASKNAME AS TASKDETAILEDTASKNAME, "
			+ "		WFG_TASKDETAILEDTASK.TASKDETAILEDTASKHOURS AS TASKDETAILEDTASKHOURS, "
			+ "		DATE_FORMAT(WFG_TASKDETAILEDTASK.TASKDETAILEDTASKDATE, '%Y-%m-%d') AS TASKDETAILEDTASKDATE "
			+ " FROM WFG_TASKDETAILEDTASK "
			+ " INNER JOIN MST_USER "
			+ "		ON WFG_TASKDETAILEDTASK.ASSIGNEDUSERID =  MST_USER.USERID  "
			+ "	INNER JOIN WFG_TASK "
			+ "		ON WFG_TASKDETAILEDTASK.TASKID = WFG_TASK.TASKID "
			+ "	INNER JOIN WFG_WORKFLOW "
			+ "     ON WFG_TASK.WORKFLOWID = WFG_WORKFLOW.WORKFLOWID "
			+ " INNER JOIN WFG_PROJECT "
			+ " 	ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " WHERE WFG_PROJECT.PROJECTID = ? ";
	
	/* Search all records in Workflow table by Project ID */
	public static String SELECTSQL_WORKFLOW_001 = "SELECT "
			+ " 	WFG_WORKFLOW.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME, "
			+ " 	WFG_WORKFLOW.WORKFLOWNAME AS WORKFLOWNAME, "
			+ " 	WFG_WORKFLOW.WORKFLOWSEQUENCE AS WORKFLOWSEQUENCE, "
			+ " 	MST_PHASE.PHASECODE AS PHASECODE, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID " 
			+ " FROM WFG_WORKFLOW "
			+ " INNER JOIN WFG_PROJECT "
			+ " 	ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " INNER JOIN MST_PHASE "
			+ " 	ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID "
			+ " WHERE WFG_WORKFLOW.PROJECTID = ? "
			+ " ORDER BY WFG_WORKFLOW.WORKFLOWSEQUENCE ";

	/* Search a record in Workflow table by Workflow ID */
	public static String SELECTSQL_WORKFLOW_002 = "SELECT "
			+ " 	WFG_WORKFLOW.WORKFLOWID AS WORKFLOWID, "
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME, "
			+ " 	WFG_WORKFLOW.WORKFLOWNAME AS WORKFLOWNAME, "
			+ " 	WFG_WORKFLOW.WORKFLOWSEQUENCE AS WORKFLOWSEQUENCE, "
			+ " 	MST_PHASE.PHASECODE AS PHASECODE, "
			+ " 	WFG_WORKFLOW.PROJECTID AS PROJECTID " + " FROM WFG_WORKFLOW "
			+ " INNER JOIN WFG_PROJECT "
			+ " 	ON WFG_WORKFLOW.PROJECTID = WFG_PROJECT.PROJECTID "
			+ " INNER JOIN MST_PHASE "
			+ " 	ON WFG_WORKFLOW.PHASEID = MST_PHASE.PHASEID "
			+ " WHERE WFG_WORKFLOW.WORKFLOWID = ? ";
	
	/* Search all records in Project Member  table by Project ID */
	public static String SELECTSQL_PROJECTMEMBER_001 = "SELECT "
			+ "		WFG_PROJECTMEMBER.PROJECTMEMBERID AS PROJECTMEMBERID, "
			+ "		WFG_PROJECTMEMBER.PROJECTID AS PROJECTID, "
			+ "		MST_USER.USERID AS USERID, "
			+ "		MST_USER.USERNAME AS USERNAME, "
			+ "		MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	WFG_PROJECTMEMBER.PROJECTMEMBERACCESS AS PROJECTMEMBERACCESS, "			 
		 	+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME," 
		 	+ " 	WFG_PROJECT.PROJECTDESCRIPTION AS PROJECTDESCRIPTION," 
			+ "  	MST_COMPANY.COMPANYNAME AS COMPANYNAME,"
			+ "  	WFG_PROJECT.PROJECTSTATUS AS PROJECTSTATUS,"
			+ " 	DATE_FORMAT(WFG_PROJECT.PROJECTSTARTDATE,'%Y-%m-%d') AS PROJECTSTARTDATE"
			+ " FROM WFG_PROJECTMEMBER " 
			+ " INNER JOIN MST_USER " 
			+ " 	ON WFG_PROJECTMEMBER.USERID = MST_USER.USERID "
			+ " INNER JOIN WFG_PROJECT " 
			+ " 	ON WFG_PROJECTMEMBER.PROJECTID = WFG_PROJECT.PROJECTID "
			+ "  INNER JOIN MST_COMPANY "
			+ "  	ON WFG_PROJECT.COMPANYID = MST_COMPANY.COMPANYID" 
			+ " WHERE WFG_PROJECT.PROJECTID = ? ";

	/* Search records in Project member table by Project member ID */
	public static String SELECTSQL_PROJECTMEMBER_002 = "SELECT "
			+ "		WFG_PROJECTMEMBER.PROJECTMEMBERID AS PROJECTMEMBERID, "
			+ "		WFG_PROJECTMEMBER.PROJECTID AS PROJECTID, "
			+ "		MST_USER.USERID AS USERID, "
			+ "		MST_USER.USERNAME AS USERNAME, "
			+ "		MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	WFG_PROJECTMEMBER.PROJECTMEMBERACCESS AS PROJECTMEMBERACCESS, "			 
 			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME," 
		 	+ " 	WFG_PROJECT.PROJECTDESCRIPTION AS PROJECTDESCRIPTION," 
			+ "  	MST_COMPANY.COMPANYNAME AS COMPANYNAME,"
			+ "  	WFG_PROJECT.PROJECTSTATUS AS PROJECTSTATUS,"
			+ "  	DATE_FORMAT(WFG_PROJECT.PROJECTSTARTDATE,'%Y-%m-%d') AS PROJECTSTARTDATE"
			+ " FROM WFG_PROJECTMEMBER " 
			+ " INNER JOIN MST_USER " 
			+ " 	ON WFG_PROJECTMEMBER.USERID = MST_USER.USERID "
			+ " INNER JOIN WFG_PROJECT " 
			+ " 	ON WFG_PROJECTMEMBER.PROJECTID = WFG_PROJECT.PROJECTID "
			+ "  INNER JOIN MST_COMPANY "
			+ "  	ON WFG_PROJECT.COMPANYID = MST_COMPANY.COMPANYID" 		
			+ " WHERE WFG_PROJECTMEMBER.PROJECTMEMBERID = ?";
	
	/* Search records in Project member table by Project member ID and Project ID*/
	public static String SELECTSQL_PROJECTMEMBER_003 = "SELECT "
			+ "		WFG_PROJECTMEMBER.PROJECTMEMBERID AS PROJECTMEMBERID, "
			+ "		WFG_PROJECTMEMBER.PROJECTID AS PROJECTID, "
			+ "		MST_USER.USERID AS USERID, "
			+ "		MST_USER.USERNAME AS USERNAME, "
			+ "		MST_USER.USERFULLNAME AS USERFULLNAME, "
			+ " 	WFG_PROJECTMEMBER.PROJECTMEMBERACCESS AS PROJECTMEMBERACCESS, "			 
 			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME," 
		 	+ " 	WFG_PROJECT.PROJECTDESCRIPTION AS PROJECTDESCRIPTION," 
			+ "  	MST_COMPANY.COMPANYNAME AS COMPANYNAME,"
			+ "  	WFG_PROJECT.PROJECTSTATUS AS PROJECTSTATUS,"
			+ " 	DATE_FORMAT(WFG_PROJECT.PROJECTSTARTDATE,'%Y-%m-%d') AS PROJECTSTARTDATE"		 
			+ " FROM WFG_PROJECTMEMBER " 
			+ " INNER JOIN MST_USER " 
			+ " 	ON WFG_PROJECTMEMBER.USERID = MST_USER.USERID "
			+ " INNER JOIN WFG_PROJECT " 
			+ " 	ON WFG_PROJECTMEMBER.PROJECTID = ? "
			+ "  INNER JOIN MST_COMPANY "
			+ "  	ON WFG_PROJECT.COMPANYID = MST_COMPANY.COMPANYID" 
			+ " WHERE WFG_PROJECTMEMBER.PROJECTMEMBERID = ? ";

	/* Search records in Project member table by Project member  User ID */
	public static String SELECTSQL_PROJECTMEMBER_004 = "SELECT "
			+ "  WFG_PROJECTMEMBER.PROJECTMEMBERID AS PROJECTMEMBERID, "
			+ "  WFG_PROJECTMEMBER.PROJECTID AS PROJECTID, "
			+ "  MST_USER.USERID AS USERID, "
			+ "  MST_USER.USERNAME AS USERNAME," 
			+ "  MST_USER.USERFULLNAME AS USERFULLNAME," 
			+ "  WFG_PROJECTMEMBER.PROJECTMEMBERACCESS AS PROJECTMEMBERACCESS," 
		 	+ "  WFG_PROJECT.PROJECTNAME AS PROJECTNAME," 
		 	+ "  WFG_PROJECT.PROJECTDESCRIPTION AS PROJECTDESCRIPTION," 
			+ "  MST_COMPANY.COMPANYNAME AS COMPANYNAME,"
			+ "  WFG_PROJECT.PROJECTSTATUS AS PROJECTSTATUS,"
			+ "  DATE_FORMAT(WFG_PROJECT.PROJECTSTARTDATE,'%Y-%m-%d') AS PROJECTSTARTDATE"	 
			+ "  FROM WFG_PROJECTMEMBER" 
			+ "  INNER JOIN MST_USER "
			+ "  	ON WFG_PROJECTMEMBER.USERID = MST_USER.USERID" 
			+ "  INNER JOIN WFG_PROJECT "
			+ " 	ON WFG_PROJECTMEMBER.PROJECTID = WFG_PROJECT.PROJECTID" 
			+ "  INNER JOIN MST_COMPANY "
			+ "  	ON WFG_PROJECT.COMPANYID = MST_COMPANY.COMPANYID" 
			+ "  WHERE WFG_PROJECTMEMBER.USERID = ?";
	
	/* Search count in Relation table */
	public static String SELECTSQL_RELATION_001 = "SELECT "
			+ " 	COUNT(*) AS COUNT " 
			+ " FROM RELATION "
			+ " WHERE RELATION.CHILDID = ? ";

	/* Search all records in Request table by Requester Id*/
	public static String SELECTSQL_REQUEST_001 = "SELECT "
			+ "		WFG_REQUEST.REQUESTID AS REQUESTID, "
			+ " 	WFG_REQUEST.REQUESTSTATUS AS REQUESTSTATUS, "
			+ " 	WFG_REQUEST.REQUESTERID AS REQUESTERID, "
			+ " 	WFG_REQUEST.REQUESTDEADLINE AS REQUESTDEADLINE, "
			+ " 	WFG_REQUEST.REQUESTHOURS AS REQUESTHOURS, "
			+ " 	WFG_PROJECT.PROJECTID AS PROJECTID, "
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME, "
			+ " 	WFG_REQUEST.REQUESTNAME AS REQUESTNAME, "
			+ " 	WFG_REQUEST.REQUESTDESCRIPTION AS REQUESTDESCRIPTION, "
			+ " 	WFG_REQUEST.REQUESTREFUSECOMMENT AS REQUESTREFUSECOMMENT, "
			+ " 	WFG_REQUEST.REQUESTPRIORITY AS REQUESTPRIORITY, "
			+ " 	MST_USER.USERNAME AS USERNAME "
			+ " FROM WFG_REQUEST " 
			+ " INNER JOIN WFG_PROJECT " 
			+ " 	ON WFG_REQUEST.PROJECTID = WFG_PROJECT.PROJECTID "			
			+ " INNER JOIN MST_USER "
			+ " 	ON WFG_REQUEST.REQUESTERID = MST_USER.USERID "
			+ "	WHERE WFG_REQUEST.REQUESTERID = ? " ;
	/* Search all records in Request table by Request Id*/
	public static String SELECTSQL_REQUEST_002 = "SELECT "
			+ "		WFG_REQUEST.REQUESTID AS REQUESTID, "
			+ " 	WFG_REQUEST.REQUESTSTATUS AS REQUESTSTATUS, "
			+ " 	WFG_REQUEST.REQUESTERID AS REQUESTERID, "
			+ " 	WFG_REQUEST.REQUESTDEADLINE AS REQUESTDEADLINE, "
			+ " 	WFG_REQUEST.REQUESTHOURS AS REQUESTHOURS, "
			+ " 	WFG_PROJECT.PROJECTID AS PROJECTID, "
			+ " 	WFG_PROJECT.PROJECTNAME AS PROJECTNAME, "
			+ " 	WFG_REQUEST.REQUESTNAME AS REQUESTNAME, "
			+ " 	WFG_REQUEST.REQUESTDESCRIPTION AS REQUESTDESCRIPTION, "
			+ " 	WFG_REQUEST.REQUESTREFUSECOMMENT AS REQUESTREFUSECOMMENT, "
			+ " 	WFG_REQUEST.REQUESTPRIORITY AS REQUESTPRIORITY, "
			+ " 	MST_USER.USERNAME AS USERNAME "
			+ " FROM WFG_REQUEST " 
			+ " INNER JOIN WFG_PROJECT " 
			+ " 	ON WFG_REQUEST.PROJECTID = WFG_PROJECT.PROJECTID "			
			+ " INNER JOIN MST_USER "
			+ " 	ON WFG_REQUEST.REQUESTERID = MST_USER.USERID "
			+ "	WHERE WFG_REQUEST.REQUESTID = ? " ;

	/* Search all records in Request table by Approver Id and Active Flag as Y*/
	public static String SELECTSQL_REQUEST_003 = "SELECT "	
			+ "		 WFG_REQUEST.REQUESTID AS REQUESTID,  "
			+ "		WFG_REQUEST.REQUESTSTATUS AS REQUESTSTATUS, "
			+ " 	WFG_REQUEST.REQUESTERID AS REQUESTERID, "
			+ "		WFG_REQUEST.REQUESTDEADLINE AS REQUESTDEADLINE," 
			+ "		WFG_REQUEST.REQUESTHOURS AS REQUESTHOURS, "
			+ "		WFG_PROJECT.PROJECTID AS PROJECTID, "
			+ "		WFG_PROJECT.PROJECTNAME AS PROJECTNAME, "
			+ "		WFG_REQUEST.REQUESTNAME AS REQUESTNAME, "
			+ "		WFG_REQUEST.REQUESTDESCRIPTION AS REQUESTDESCRIPTION," 
			+ "		WFG_REQUEST.REQUESTREFUSECOMMENT AS REQUESTREFUSECOMMENT," 
			+ "		WFG_REQUEST.REQUESTPRIORITY AS REQUESTPRIORITY, "
			+ "		WFG_REQUESTAPPROVER.ACTIVEFLAG AS ACTIVEFLAG, "
			+ "		MST_USER.USERNAME AS USERNAME "
			+ "	FROM WFG_REQUEST"
			+ "	INNER JOIN WFG_REQUESTAPPROVER"
			+ "		ON WFG_REQUEST.REQUESTID = WFG_REQUESTAPPROVER.REQUESTID" 	
			+ "	INNER JOIN WFG_PROJECT "
			+ "		ON WFG_REQUEST.PROJECTID = WFG_PROJECT.PROJECTID" 	
			+ "	INNER JOIN MST_USER "
			+ "		ON WFG_REQUEST.REQUESTERID = MST_USER.USERID"  
			+ "	WHERE WFG_REQUESTAPPROVER.APPROVERID = ? "
			+ "	AND WFG_REQUESTAPPROVER.ACTIVEFLAG = ? ";
	
	/* Search all records in Request Table and RequestApprover Table by RequestApprover ID */
	public static String SELECTSQL_REQUEST_004 = "SELECT "	
			+ "		WFG_REQUEST.REQUESTID AS REQUESTID,  "
			+ "		WFG_REQUEST.REQUESTSTATUS AS REQUESTSTATUS," 
			+ "		WFG_REQUEST.REQUESTERID AS REQUESTERID, "
			+ "		WFG_REQUEST.REQUESTDEADLINE AS REQUESTDEADLINE,"
			+ "		WFG_REQUEST.REQUESTHOURS AS REQUESTHOURS, "
			+ "		WFG_PROJECT.PROJECTID AS PROJECTID, "
			+ "		WFG_PROJECT.PROJECTNAME AS PROJECTNAME," 
			+ "		WFG_REQUEST.REQUESTNAME AS REQUESTNAME, "
			+ "		WFG_REQUEST.REQUESTDESCRIPTION AS REQUESTDESCRIPTION,"
			+ "		WFG_REQUEST.REQUESTREFUSECOMMENT AS REQUESTREFUSECOMMENT,"
			+ "		WFG_REQUEST.REQUESTPRIORITY AS REQUESTPRIORITY,"
			+ "		WFG_REQUESTAPPROVER.APPROVERID AS APPROVERID,"
			+ "		MST_USER.USERNAME AS USERNAME "
			+ "		FROM WFG_REQUEST"
			+ "		INNER JOIN WFG_REQUESTAPPROVER"
			+ "			ON WFG_REQUEST.REQUESTID = WFG_REQUESTAPPROVER.REQUESTID"	
			+ "		INNER JOIN WFG_PROJECT "
			+ "			ON WFG_REQUEST.PROJECTID = WFG_PROJECT.PROJECTID"
			+ "		INNER JOIN MST_USER "
			+ "			ON  WFG_REQUEST.REQUESTERID = MST_USER.USERID" 
			+ "		WHERE  WFG_REQUEST.REQUESTERID	=  ? " 
			+ "        OR  (WFG_REQUESTAPPROVER.APPROVERID  =  ?" 
			+ "        AND WFG_REQUESTAPPROVER.ACTIVEFLAG = ?)"
			+ "		GROUP BY WFG_REQUEST.REQUESTID";
			
	/* Search all records in Request Approver  table by Request ID */
	public static String SELECTSQL_REQUESTAPPROVER_001 = "SELECT "
			+ "		WFG_REQUESTAPPROVER.REQUESTAPPROVERID AS REQUESTAPPROVERID, "
			+ "		WFG_REQUESTAPPROVER.REQUESTID AS REQUESTID, "
			+ "		WFG_REQUESTAPPROVER.APPROVERID AS APPROVERID, "
			+ "		WFG_REQUESTAPPROVER.REQUESTSTATUS AS REQUESTSTATUS, "
			+ "		WFG_REQUESTAPPROVER.REQUESTORDER AS REQUESTORDER, "
			+ "		WFG_REQUESTAPPROVER.COMPLETEDFLAG AS COMPLETEDFLAG, "
			+ "		WFG_REQUESTAPPROVER.ACTIVEFLAG AS ACTIVEFLAG, "
			+ "		MST_USER.USERNAME AS USERNAME "			
			+ " FROM WFG_REQUESTAPPROVER " 
			+ " INNER JOIN MST_USER " 
			+ " 	ON WFG_REQUESTAPPROVER.APPROVERID = MST_USER.USERID "
			+ " WHERE WFG_REQUESTAPPROVER.REQUESTID = ? ";
	
	/* Search all records in Request Approver table by Request Id and Requester Id*/
	public static String SELECTSQL_REQUESTAPPROVER_002 = "SELECT "
			+ "		WFG_REQUESTAPPROVER.REQUESTAPPROVERID AS REQUESTAPPROVERID, "
			+ "		WFG_REQUESTAPPROVER.REQUESTID AS REQUESTID, "
			+ "		WFG_REQUESTAPPROVER.APPROVERID AS APPROVERID, "
			+ "		WFG_REQUESTAPPROVER.REQUESTSTATUS AS REQUESTSTATUS, "
			+ "		WFG_REQUESTAPPROVER.REQUESTORDER AS REQUESTORDER, "
			+ "		WFG_REQUESTAPPROVER.COMPLETEDFLAG AS COMPLETEDFLAG, "
			+ "		WFG_REQUESTAPPROVER.ACTIVEFLAG AS ACTIVEFLAG, "
			+ "		MST_USER.USERNAME AS USERNAME "			
			+ " FROM WFG_REQUESTAPPROVER " 
			+ " INNER JOIN MST_USER " 
			+ " 	ON WFG_REQUESTAPPROVER.APPROVERID = MST_USER.USERID "
			+ " WHERE WFG_REQUESTAPPROVER.REQUESTID = ? "
			+ "	AND WFG_REQUESTAPPROVER.APPROVERID = ? ";
	
	/* Search all records in Request Approver table by Request Id and Request Order*/
	public static String SELECTSQL_REQUESTAPPROVER_003 = "SELECT "
			+ "		WFG_REQUESTAPPROVER.REQUESTAPPROVERID AS REQUESTAPPROVERID, "
			+ "		WFG_REQUESTAPPROVER.REQUESTID AS REQUESTID, "
			+ "		WFG_REQUESTAPPROVER.APPROVERID AS APPROVERID, "
			+ "		WFG_REQUESTAPPROVER.REQUESTSTATUS AS REQUESTSTATUS, "
			+ "		WFG_REQUESTAPPROVER.REQUESTORDER AS REQUESTORDER, "
			+ "		WFG_REQUESTAPPROVER.APPROVERID AS APPROVERID, "
			+ "		WFG_REQUESTAPPROVER.COMPLETEDFLAG AS COMPLETEDFLAG, "
			+ "		WFG_REQUESTAPPROVER.ACTIVEFLAG AS ACTIVEFLAG, "
			+ "		MST_USER.USERNAME AS USERNAME "			
			+ " FROM WFG_REQUESTAPPROVER " 
			+ " INNER JOIN MST_USER " 
			+ " 	ON WFG_REQUESTAPPROVER.APPROVERID = MST_USER.USERID "
			+ " WHERE WFG_REQUESTAPPROVER.REQUESTID = ? "
			+ "	AND WFG_REQUESTAPPROVER.REQUESTORDER = ? ";
	
	/* Search all records in Request Approver table by Request Id and Requester Id*/
	public static String SELECTSQL_REQUESTAPPROVER_004 = "SELECT "
			+ "		WFG_REQUESTAPPROVER.REQUESTAPPROVERID AS REQUESTAPPROVERID, "
			+ "		WFG_REQUESTAPPROVER.REQUESTID AS REQUESTID, "
			+ "		WFG_REQUESTAPPROVER.APPROVERID AS APPROVERID, "
			+ "		WFG_REQUESTAPPROVER.REQUESTSTATUS AS REQUESTSTATUS, "
			+ "		WFG_REQUESTAPPROVER.REQUESTORDER AS REQUESTORDER, "
			+ "		WFG_REQUESTAPPROVER.COMPLETEDFLAG AS COMPLETEDFLAG, "
			+ "		WFG_REQUESTAPPROVER.ACTIVEFLAG AS ACTIVEFLAG, "
			+ "		MST_USER.USERNAME AS USERNAME "			
			+ " FROM WFG_REQUESTAPPROVER " 
			+ " INNER JOIN MST_USER " 
			+ " 	ON WFG_REQUESTAPPROVER.APPROVERID = MST_USER.USERID "
			+ " WHERE WFG_REQUESTAPPROVER.REQUESTAPPROVERID = ? ";

		
	/** SQL Update */

	/* Update in Company table */
	public static String UPDATESQL_COMPANY_001 = "UPDATE MST_COMPANY "
			+ " SET COMPANYCODE = ?, " 
			+ " 	COMPANYNAME = ? "
			+ " WHERE COMPANYID = ? ";

	/* Update in Document Type table */
	public static String UPDATESQL_DOCUMENTTYPE_001 = "UPDATE MST_DOCUMENTTYPE "
			+ " SET DOCUMENTTYPECODE = ?, "
			+ " 	DOCUMENTTYPENAME = ? "
			+ " WHERE DOCUMENTTYPEID = ? ";

	/* Update in Phase table */
	public static String UPDATESQL_PHASE_001 = "UPDATE MST_PHASE "
			+ " SET PHASECODE = ?, " 
			+ " 	PHASENAME = ? "
			+ " WHERE PHASEID = ? ";

	/* Update in Module table */
	public static String UPDATESQL_MODULE_001 = "UPDATE MST_MODULE "
			+ " SET MODULENAME = ?, "
			+ "     MODULESEQUENCE = ?, "
			+ "     URLPATTERN = ? "
			+ " WHERE MODULEID = ? ";
	
	/* Update in Program table */
	public static String UPDATESQL_PROGRAM_001 = "UPDATE MST_PROGRAM "
			+ " SET PROGRAMNAME = ?, "
			+ "     MODULEID = ?, "
			+ "     JAVASERVLETREFERENCE = ?, "
			+ "     URLPATTERN = ?, "
			+ "     WITHINTHEMENU = ? "
			+ " WHERE PROGRAMID = ? ";
	
	/* Update in Access Type table */
	public static String UPDATESQL_ACCESSTYPE_001 = "UPDATE MST_ACCESSTYPE "
			+ " SET ACCESSTYPECODE = ?, " + " 	ACCESSTYPENAME = ? "
			+ " WHERE ACCESSTYPEID = ? ";
	
	/* Update in Access Type Detail table */
	public static String UPDATESQL_ACCESSTYPEDETAIL_001 = "UPDATE MST_ACCESSTYPEDETAIL "
			+ " SET PROGRAMID = ?, " 
			+ " 	ACCESSRIGHT = ? " 
			+ " WHERE ACCESSTYPEDETAILID = ? ";
	
	/* Update in User table */
	public static String UPDATESQL_USER_001 = "UPDATE MST_USER "
			+ " SET USERPASSWORD = ?, " 
			+ " 	USERFULLNAME = ?, "
			+ " 	COMPANYID = ?, " 
			+ " 	USEREMAIL = ?, " 
			+ " 	USERNAME = ?, "
			+ " 	ACCESSTYPEID = ?, "
			+ "     VALIDFROM = ?, "
			+ "     VALIDTO = ? "
			+ " WHERE USERID = ? ";

	/* Update Reset Password Key in User table */
	public static String UPDATESQL_USER_002 = "UPDATE MST_USER "
			+ " SET RESETPASSWORDKEY = ? " 
			+ " WHERE USERID = ? ";

	/* Update User Password in User table */
	public static String UPDATESQL_USER_003 = "UPDATE MST_USER "
			+ " SET USERPASSWORD = ?, " 
			+ "     RESETPASSWORDKEY = ? "
			+ " WHERE RESETPASSWORDKEY = ? ";

	/* Update in Vocabulary table */
	public static String UPDATESQL_VOCABULARY_001 = "UPDATE MST_VOCABULARY "
			+ " SET VOCABNAME = ?, " 
			+ " 	VOCABDESCRIPTION = ?, "
			+ " 	VOCABCATEGORYID = ? " 
			+ " WHERE VOCABID = ? ";

	/* Update in Vocabulary Category table */
	public static String UPDATESQL_VOCABULARY_CATEGORY_001 = "UPDATE MST_VOCABULARYCATEGORY "
			+ " SET VOCABCATEGORYNAME = ?, "
			+ " 	VOCABCATEGORYPARENTID = ?, "
			+ " 	VOCABCATEGORYDESC = ? " 
			+ " WHERE VOCABCATEGORYID = ? ";

	/* Update in Project table */
	public static String UPDATESQL_PROJECT_001 = "UPDATE WFG_PROJECT "
			+ " SET PROJECTNAME = ?, " 
			+ " 	PROJECTDESCRIPTION = ?, "
			+ " 	COMPANYID = ?, " 
			+ " 	PROJECTSTATUS = ?, "
			+ " 	PROJECTSTARTDATE = ? "
			+ " WHERE PROJECTID = ? ";

	/* Update in Task table */
	public static String UPDATESQL_TASK_001 = "UPDATE WFG_TASK "
			+ " SET TASKNAME = ?, "
			+ "     TASKWORKPOINTS = ?, " 
			+ "     TASKTOTALHOURS = ?, "
			+ "     TASKPROGRESS = ?, " 
			+ "     TASKDEADLINE = ?, "
			+ "     TASKPLANINFOPLANNEDHOURS = ?, " 
			+ "     TASKPLANINFOPRIORITY = ?, " 
			+ "     TASKPLANINFOSTARTDATE = ?, " 
			+ "     TASKPLANINFOENDDATE = ?, " 
			+ "     TASKPLANINFOCOMMENT = ?, " 
			+ "     TASKACTIVITYINFOSTATUS = ? "
		    + "WHERE TASKID = ? ";

	/* Update in Task Checkpoint table */
	public static String UPDATESQL_TASK_CHECKPOINT_001 = "UPDATE WFG_TASKCHECKPOINT "
			+ " SET TASKDOCUMENTID = ?, "
			+ " 	TASKCHECKPOINTNAME = ?, "
			+ " 	TASKCHECKPOINTDESCRIPTION = ? "
			+ " WHERE TASKCHECKPOINTID = ? ";

	/* Update in Task Document table */
	public static String UPDATESQL_TASK_DOCUMENT_001 = "UPDATE WFG_TASKDOCUMENT "
			+ " SET TASKID = ?, "
			+ " 	TASKDOCUMENTINPUTOUTPUT = ?, "
			+ " 	DOCUMENTTYPEID = ?, "
			+ " 	TASKDOCUMENTNAME = ?, "
			+ " 	TASKDOCUMENTPATH = ?, "
			+ " 	TASKDOCUMENTFILE = ? "
			+ " WHERE TASKDOCUMENTID = ? ";

	/* Update in Task Document table without Document File */
	public static String UPDATESQL_TASK_DOCUMENT_002 = "UPDATE WFG_TASKDOCUMENT "
			+ " SET TASKID = ?, "
			+ " 	TASKDOCUMENTINPUTOUTPUT = ?, "
			+ " 	DOCUMENTTYPEID = ?, "
			+ " 	TASKDOCUMENTNAME = ? "
			+ " WHERE TASKDOCUMENTID = ? ";

	/* Update in Workflow table */
	public static String UPDATESQL_WORKFLOW_001 = "UPDATE WFG_WORKFLOW "
			+ " SET WORKFLOWNAME = ?, " 
			+ " 	WORKFLOWSEQUENCE = ?, "
			+ " 	PHASEID = ? " 
			+ " WHERE WORKFLOWID = ? ";
	
	/* Update in ProjectMember table */
	public static String UPDATESQL_PROJECTMEMBER_001 = "UPDATE WFG_PROJECTMEMBER "
			+ " SET USERID = ?, " 
			+ " 	PROJECTMEMBERACCESS = ? "
			+ " WHERE PROJECTMEMBERID = ? ";
	
	/* Update in Request table */
	public static String UPDATESQL_REQUEST_001 = "UPDATE WFG_REQUEST "
	+ " SET REQUESTSTATUS = ?, "	
	+ " 	REQUESTERID = ?, "
	+ " 	REQUESTDEADLINE = ?, "
	+ " 	REQUESTHOURS = ?, " 
	+ " 	PROJECTID = ?, "
	+ " 	REQUESTNAME = ?, "
	+ " 	REQUESTDESCRIPTION = ?, "
	+ " 	REQUESTREFUSECOMMENT = ?, " 
	+ " 	REQUESTPRIORITY = ? "
	+ " WHERE REQUESTID = ? ";
	

	/* Update in Request Approver table */
	public static String UPDATESQL_REQUESTAPPROVER_001 = "UPDATE WFG_REQUESTAPPROVER "	
			+ " SET	APPROVERID  = ?, "
			+ " 	REQUESTID  = ?, "
			+ " 	REQUESTSTATUS = ?, " 
			+ " 	REQUESTORDER = ?, "
			+ " 	COMPLETEDFLAG = ?, "
			+ " 	ACTIVEFLAG = ? "
			+ " WHERE REQUESTAPPROVERID = ?" ;

	/* Update in Relation table */
	public static String UPDATESQL_RELATION_001 = "UPDATE RELATION "
			+ " SET CHILDID = ? " 
			+ " WHERE PARENTID = ? AND " 
			+ "       CHILDTABLE = ? ";
	
	/** SQL Insert */

	/* Insert in Company table */
	public static String INSERTSQL_COMPANY_001 = "INSERT INTO MST_COMPANY "
			+ "(COMPANYID, " 
			+ " COMPANYCODE, " 
			+ " COMPANYNAME) "
			+ " VALUES (?, ?, ?) ";

	/* Insert in Document Type table */
	public static String INSERTSQL_DOCUMENTTYPE_001 = "INSERT INTO MST_DOCUMENTTYPE "
			+ "(DOCUMENTTYPEID, "
			+ " DOCUMENTTYPECODE, "
			+ " DOCUMENTTYPENAME) " 
			+ " VALUES (?, ?, ?) ";

	/* Insert in Phase table */
	public static String INSERTSQL_PHASE_001 = "INSERT INTO MST_PHASE "
			+ "(PHASEID, " 
			+ " PHASECODE, " 
			+ " PHASENAME) "
			+ " VALUES (?, ?, ?) ";

	/* Insert in Module table */
	public static String INSERTSQL_MODULE_001 = "INSERT INTO MST_MODULE " 
			+ "(MODULEID, " 
			+ " MODULENAME, "
			+ " MODULESEQUENCE, "
			+ " URLPATTERN) "
			+ " VALUES (?, ?, ?, ?) ";
	
	/* Insert in Program table */
	public static String INSERTSQL_PROGRAM_001 = "INSERT INTO MST_PROGRAM " 
			+ "(PROGRAMID, " 
			+ " PROGRAMNAME, "
			+ " MODULEID, "
			+ " JAVASERVLETREFERENCE, "
			+ " URLPATTERN, "
			+ " WITHINTHEMENU) "
			+ " VALUES (?, ?, ?, ?, ?, ?) ";
	
	/* Insert in Access Type table */
	public static String INSERTSQL_ACCESSTYPE_001 = "INSERT INTO MST_ACCESSTYPE "
			+ "(ACCESSTYPEID, " 
			+ " ACCESSTYPECODE, " 
			+ " ACCESSTYPENAME) "
			+ " VALUES (?, ?, ?) ";
	
	/* Insert in Access Type Detail table */
	public static String INSERTSQL_TASK_ACCESSTYPEDETAIL_001 = "INSERT INTO MST_ACCESSTYPEDETAIL "
			+ "(ACCESSTYPEDETAILID, "
			+ " ACCESSTYPEID, "
			+ " PROGRAMID, "
			+ " ACCESSRIGHT) " 
			+ " VALUES (?, ?, ?, ?) ";
	
	/* Insert in User table */
	public static String INSERTSQL_USER_001 = "INSERT INTO MST_USER "
			+ "(USERID, " 
			+ " USERNAME, " 
			+ " USERPASSWORD, "
			+ " USERFULLNAME, " 
			+ " USEREMAIL, " 
			+ " COMPANYID, "
			+ " ACCESSTYPEID, "
			+ " VALIDFROM, "
			+ " VALIDTO) "
			+ " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ";

	/* Insert in Vocabulary table */
	public static String INSERTSQL_VOCABULARY_001 = "INSERT INTO MST_VOCABULARY "
			+ "(VOCABID, "
			+ " VOCABNAME, "
			+ " VOCABDESCRIPTION, "
			+ " VOCABCATEGORYID) " 
			+ " VALUES (?, ?, ?, ?) ";

	/* Insert in Project table */
	public static String INSERTSQL_PROJECT_001 = "INSERT INTO WFG_PROJECT "
			+ "(PROJECTID, " 
			+ " PROJECTNAME, " 
			+ " PROJECTDESCRIPTION, "
			+ " COMPANYID, " 
			+ " PROJECTSTATUS, " 
			+ " PROJECTSTARTDATE) " 
			+ " VALUES (?, ?, ?, ?, ?, ?) ";

	/* Insert in Task table */
	public static String INSERTSQL_TASK_001 = "INSERT INTO WFG_TASK "
			+ "(TASKID, " 
			+ " WORKFLOWID, " 
			+ " TASKNAME, "
			+ " TASKWORKPOINTS, " 
			+ " TASKDEADLINE, " 
			+ " TASKACTIVITYINFOSTATUS) " 
			+ " VALUES (?, ?, ?, ?, ?, ?) ";

	/* Insert in Task Checkpoint table */
	public static String INSERTSQL_TASK_CHECKPOINT_001 = "INSERT INTO WFG_TASKCHECKPOINT "
			+ "(TASKCHECKPOINTID, "
			+ " TASKDOCUMENTID, "
			+ " TASKCHECKPOINTNAME, "
			+ " TASKCHECKPOINTDESCRIPTION) "
			+ " VALUES (?, ?, ?, ?) ";

	/* Insert in Task Document table */
	public static String INSERTSQL_TASK_DOCUMENT_001 = "INSERT INTO WFG_TASKDOCUMENT "
			+ "(TASKDOCUMENTID, "
			+ " TASKID, "
			+ " TASKDOCUMENTINPUTOUTPUT, "
			+ " DOCUMENTTYPEID, "
			+ " TASKDOCUMENTNAME, "
			+ " TASKDOCUMENTPATH, "
			+ " TASKDOCUMENTFILE) "
			+ " VALUES (?, ?, ?, ?, ?, ?, ?) ";

	/* Insert in Task Prerequisite table */
	public static String INSERTSQL_TASK_PREREQUISITE_001 = "INSERT INTO WFG_TASKPREREQ "
			+ "(TASKPREREQID, "
			+ " TASKIDPARENT, "
			+ " TASKIDCHILD) "
			+ " VALUES (?, ?, ?) ";
	
	/* Insert in Task Assigned User table */
	public static String INSERTSQL_TASK_ASSIGNEDUSER_001 = "INSERT INTO WFG_TASKASSIGNEDUSER "
			+ "(TASKASSIGNEDUSERID, "
			+ " TASKID, "
			+ " USERID) "
			+ " VALUES (?, ?, ?) ";
	
	/* Insert in Task Detailed Task User table */
	public static String INSERTSQL_TASK_DETAILEDTASK_001 = "INSERT INTO WFG_TASKDETAILEDTASK "
			+ "(TASKDETAILEDTASKID, "
			+ " TASKID, "
			+ " TASKDETAILEDTASKNAME,"
			+ " ASSIGNEDUSERID, "
			+ " TASKDETAILEDTASKHOURS, "
			+ " TASKDETAILEDTASKDATE) "
			+ " VALUES (?, ?, ?, ?, ?, ?) ";

	/* Insert in Workflow table */
	public static String INSERTSQL_TASK_WORKFLOW_001 = "INSERT INTO WFG_WORKFLOW "
			+ "(WORKFLOWID, "
			+ " WORKFLOWNAME, "
			+ " PROJECTID, "
			+ " WORKFLOWSEQUENCE, " 
			+ " PHASEID) " 
			+ " VALUES (?, ?, ?, ?, ?) ";

	/* Insert in Relation table */
	public static String INSERTSQL_RELATION_001 = "INSERT INTO RELATION "
			+ "(PARENTID, "
			+ " PARENTTABLE, " 
			+ " CHILDID, " 
			+ " CHILDTABLE) "
			+ " VALUES (?, ?, ?, ?) ";
	
	/* Insert in ProjectMember table */
	public static String INSERTSQL_PROJECTMEMBER_001 = "INSERT INTO WFG_PROJECTMEMBER "
			+ "(PROJECTMEMBERID, " 
			+ " PROJECTID, " 
			+ " USERID, " 
			+ " PROJECTMEMBERACCESS) "
			+ " VALUES (?, ?, ?, ?) ";
	
	/* Insert in Request table */
	public static String INSERTSQL_REQUEST_001 = "INSERT INTO WFG_REQUEST  "
			+ " (REQUESTID, " 
			+ "  REQUESTSTATUS,"		
			+ "  REQUESTERID, "	
			+ "  REQUESTDEADLINE, "
			+ "  REQUESTHOURS, " 
			+ "  PROJECTID,"
			+ "  REQUESTNAME, "
			+ "  REQUESTDESCRIPTION, "
			+ "  REQUESTREFUSECOMMENT, " 
			+ "  REQUESTPRIORITY) "
			+ " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
	
	/* Insert in Request Approver table */
	public static String INSERTSQL_REQUESTAPPROVER_001 = "INSERT INTO WFG_REQUESTAPPROVER  "
			+ " (REQUESTAPPROVERID, " 
			+ "  REQUESTID,"		
			+ "  APPROVERID, "	
			+ "  REQUESTSTATUS, "
			+ "  REQUESTORDER, " 
			+ "  COMPLETEDFLAG,"
			+ "  ACTIVEFLAG) "
			+ " VALUES (?, ?, ?, ?, ?, ?, ?) ";

	/** SQL Delete */

	/* Delete in Company table */
	public static String DELETESQL_COMPANY_001 = "DELETE FROM MST_COMPANY WHERE COMPANYID = ? ";

	/* Delete in Document Type table */
	public static String DELETESQL_DOCUMENTTYPE_001 = "DELETE FROM MST_DOCUMENTTYPE WHERE DOCUMENTTYPEID = ? ";

	/* Delete in Phase table */
	public static String DELETESQL_PHASE_001 = "DELETE FROM MST_PHASE WHERE PHASEID = ? ";

	/* Delete in Module table */
	public static String DELETESQL_MODULE_001 = "DELETE FROM MST_MODULE WHERE MODULEID = ? ";
	
	/* Delete in Program table */
	public static String DELETESQL_PROGRAM_001 = "DELETE FROM MST_PROGRAM WHERE PROGRAMID = ? ";
	
	/* Delete in Access Type table */
	public static String DELETESQL_ACCESSTYPE_001 = "DELETE FROM MST_ACCESSTYPE WHERE ACCESSTYPEID = ? ";
	
	/* Delete in Access Type Detail table */
	public static String DELETESQL_ACCESSTYPEDETAIL_001 = "DELETE FROM MST_ACCESSTYPEDETAIL WHERE ACCESSTYPEDETAILID = ? ";
	
	/* Delete in User table */
	public static String DELETESQL_USER_001 = "DELETE FROM MST_USER WHERE USERID = ? ";

	/* Delete in Vocabulary table */
	public static String DELETESQL_VOCABULARY_001 = "DELETE FROM MST_VOCABULARY WHERE VOCABID = ? ";

	/* Delete in Project table */
	public static String DELETESQL_PROJECT_001 = "DELETE FROM WFG_PROJECT WHERE PROJECTID = ? ";

	/* Delete in Task table */
    public static String DELETESQL_TASK_001 = "DELETE FROM WFG_TASK WHERE TASKID = ? ";

	/* Delete in Task Checkpoint table */
	public static String DELETESQL_TASK_CHECKPOINT_001 = "DELETE FROM WFG_TASKCHECKPOINT WHERE TASKCHECKPOINTID = ? ";

	/* Delete in Task Document table */
	public static String DELETESQL_TASK_DOCUMENT_001 = "DELETE FROM WFG_TASKDOCUMENT WHERE TASKDOCUMENTID = ? ";

	/* Delete in Task Prerequisite table */
    public static String DELETESQL_TASK_PREREQUISITE_001 = "DELETE FROM WFG_TASKPREREQ WHERE TASKPREREQID = ? ";
	
	/* Delete in Task AssignedUser table */
	public static String DELETESQL_TASK_ASSIGNEDUSER_001 = "DELETE FROM WFG_TASKASSIGNEDUSER WHERE TASKASSIGNEDUSERID = ? ";
	
	/* Delete in Task Detailed Task table */
	public static String DELETESQL_TASK_DETAILEDTASK_001 = "DELETE FROM WFG_TASKDETAILEDTASK WHERE TASKDETAILEDTASKID = ? ";

	/* Delete in Workflow table */
	public static String DELETESQL_WORKFLOW_001 = "DELETE FROM WFG_WORKFLOW WHERE WORKFLOWID = ? ";

	/* Delete in Relation table */
	public static String DELETESQL_RELATION_001 = "DELETE FROM RELATION WHERE PARENTID = ? ";
	
	/* Delete in Project Member table */
	public static String DELETESQL_PROJECTMEMBER_001 = "DELETE FROM WFG_PROJECTMEMBER WHERE PROJECTMEMBERID = ? ";
	
	/* Delete in Request  table */
	public static String DELETESQL_REQUEST_001 = "DELETE FROM WFG_REQUEST WHERE REQUESTID = ? ";
	
	/* Delete in Request Approver  table */
	public static String DELETESQL_REQUESTAPPROVER_001 = "DELETE FROM WFG_REQUESTAPPROVER WHERE REQUESTAPPROVERID = ? ";
}
